# ANTARES Cumulative Nightly History

This notebook builds the RSP/platform-backed LSST-only nightly history store without replacing the normal `alerts_time_comparison.ipynb` workflow.

In [1]:
from pathlib import Path
import sys

REPO_URL = 'https://github.com/darim1151/ANTARES_Analysis.git'
IN_COLAB = 'google.colab' in str(get_ipython())

if IN_COLAB:
    %cd /content
    !rm -rf ANTARES_Analysis
    !git clone {REPO_URL}
    %cd ANTARES_Analysis
    !git pull --ff-only
    PROJECT_ROOT = Path('/content/ANTARES_Analysis')
else:
    PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print('Project root:', PROJECT_ROOT)
print('src files:', sorted(path.name for path in (PROJECT_ROOT / 'src').iterdir()))

Project root: /home/mdarim/notebooks/ANTARES_Analysis
src files: ['__init__.py', '__pycache__', 'cache.py', 'chunked_query.py', 'config.py', 'figures.py', 'history.py', 'lightcurves.py', 'query.py', 'summary.py', 'validation.py']

In [2]:
%pip install --quiet antares-client elasticsearch-dsl astropy matplotlib pandas numpy pyarrow

WARNING: Error parsing dependencies of lsst-display-firefly: Invalid version: 'gf67bdafdda+5c6313fe9a'
WARNING: Error parsing dependencies of astshim: Invalid version: 'g2cef7863aa+3bd8df3d95'
WARNING: Error parsing dependencies of lsst-log: Invalid version: 'ge278dab8ac+50e2446c94'
WARNING: Error parsing dependencies of lsst-sphgeom: Invalid version: 'gffca2db377+fcb1d3bbc8'
WARNING: Error parsing dependencies of lsst-geom: Invalid version: 'g90f42f885a+fce05a46d3'
WARNING: Error parsing dependencies of lsst-pex-config: Invalid version: 'g86c591e316+6e13bcb9e9'
WARNING: Error parsing dependencies of lsst-pex-exceptions: Invalid version: 'g786e29fd12+cf7ec2a62a'
WARNING: Error parsing dependencies of lsst-base: Invalid version: 'g53246c7159+fcb1d3bbc8'
WARNING: Error parsing dependencies of lsst-cpputils: Invalid version: 'g87389fa792+1e0a283bba'
WARNING: Error parsing dependencies of lsst-sconsutils: Invalid version: 'ga067d4dfce'
WARNING: Error parsing dependencies of lsst-utils: Invalid version: 'g8fa50ef3f3+fcb1d3bbc8'
WARNING: Error parsing dependencies of lsst-daf-base: Invalid version: 'gd16ba4ae74+5402bcf54a'
WARNING: Error parsing dependencies of lsst-afw: Invalid version: 'gde280f09ee+604b327636'
WARNING: Error parsing dependencies of lsst-dax-images-cutout: Invalid version: 'gbef2fa0fcc+699f635b0d'
WARNING: Error parsing dependencies of lsst-analysis-ap: Invalid version: 'g7299995a7b+de43f26a86'
WARNING: Error parsing dependencies of lsst-display-astrowidgets: Invalid version: 'ge410e46f29+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-drp-pipe: Invalid version: 'gfa42cc74b2+12d54784e9'
WARNING: Error parsing dependencies of lsst-atmospec: Invalid version: 'g3c80eed8fa+451159008f'
WARNING: Error parsing dependencies of lsst-cp-verify: Invalid version: 'gaea975da16+78a5bceb3f'
WARNING: Error parsing dependencies of lsst-faro: Invalid version: 'gd4712f2518+a5dc36a2e9'
WARNING: Error parsing dependencies of lsst-display-matplotlib: Invalid version: 'g67b6fd64d1+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-ap-verify: Invalid version: 'g331b20b0e8+154c056fd8'
WARNING: Error parsing dependencies of lsst-jointcal: Invalid version: 'g95a1e89356+47d08a1cc6'
WARNING: Error parsing dependencies of lsst-cbp: Invalid version: 'g7a6b8c32e4+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-obs-fiberspectrograph: Invalid version: 'g49223bffc5+71fbaec03f'
WARNING: Error parsing dependencies of lsst-obs-rubingenericcamera: Invalid version: 'gedca799cae+71fbaec03f'
WARNING: Error parsing dependencies of lsst-obs-cfht: Invalid version: 'g8219804093+89c0c32aaf'
WARNING: Error parsing dependencies of lsst-multiprofit: Invalid version: 'gb1c7dd4777+8835d3f417'
WARNING: Error parsing dependencies of lsst-meas-extensions-multiprofit: Invalid version: 'gbe240aa677+ea4df26a21'
WARNING: Error parsing dependencies of lsst-rucio-register: Invalid version: 'g695499c308+629b15bb59'
WARNING: Error parsing dependencies of lsst-ctrl-bps-parsl: Invalid version: 'gc6d400860b+0599d5dd00'
WARNING: Error parsing dependencies of lsst-ctrl-bps-panda: Invalid version: 'g3bba544870+0599d5dd00'
WARNING: Error parsing dependencies of lsst-lsst-bps-plugins: Invalid version: 'g7de033f5be+c2c0085595'
WARNING: Error parsing dependencies of lsst-ctrl-platform-s3df: Invalid version: 'ge69077b642+95e447aaf1'
WARNING: Error parsing dependencies of lsst-ctrl-bps: Invalid version: 'g27700a907c+db31381f2c'
WARNING: Error parsing dependencies of lsst-ctrl-bps-htcondor: Invalid version: 'g994f7ef3af+0599d5dd00'
WARNING: Error parsing dependencies of lsst-ctrl-execute: Invalid version: 'ga8b749554a+cafdd62882'
WARNING: Error parsing dependencies of lsst-display-ds9: Invalid version: 'gb89ab40317+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-meas-extensions-simpleshape: Invalid version: 'gdab6d2f7ff+37fc0c974d'
WARNING: Error parsing dependencies of lsst-meas-transinet: Invalid version: 'gd42b450c19+37fc0c974d'
WARNING: Error parsing dependencies of lsst-source-injection: Invalid version: 'g373392b20a+78a5bceb3f'
WARNING: Error parsing dependencies of lsst-cell-coadds: Invalid version: 'g2f0d04db28+cf811fdd91'
WARNING: Error parsing dependencies of lsst-drp-tasks: Invalid version: 'g105374b87b+02000fc885'
WARNING: Error parsing dependencies of lsst-fgcmcal: Invalid version: 'g21d47ad084+8e51fce9ac'
WARNING: Error parsing dependencies of lsst-obs-lsst: Invalid version: 'gf7d08d6357+4f42875b62'
WARNING: Error parsing dependencies of lsst-ctrl-mpexec: Invalid version: 'ge10c2aeecd+d8b3cefe0c'
WARNING: Error parsing dependencies of lsst-obs-decam: Invalid version: 'g0fba68d861+5616995c1c'
WARNING: Error parsing dependencies of lsst-obs-subaru: Invalid version: 'ge43c9703ef+33f09d4498'
WARNING: Error parsing dependencies of lsst-cp-pipe: Invalid version: 'gd43047442e+3bd028e7b0'
WARNING: Error parsing dependencies of lsst-analysis-tools: Invalid version: 'g8cf3414d9b+1118068a56'
WARNING: Error parsing dependencies of lsst-ap-association: Invalid version: 'g5873b1ba15+5d936c9bba'
WARNING: Error parsing dependencies of lsst-ap-pipe: Invalid version: 'gf4de327013+206014254b'
WARNING: Error parsing dependencies of lsst-scarlet-lite: Invalid version: 'gd9a9a58781+fcb1d3bbc8'
WARNING: Error parsing dependencies of lsst-meas-extensions-scarlet: Invalid version: 'g051bbdaec3+d946ffc114'
WARNING: Error parsing dependencies of lsst-meas-extensions-psfex: Invalid version: 'gc4e39d7843+4e09c98c3d'
WARNING: Error parsing dependencies of lsst-meas-extensions-piff: Invalid version: 'g36ff55ed5b+2420ccdea7'
WARNING: Error parsing dependencies of lsst-meas-extensions-gaap: Invalid version: 'g3170eb2703+d7ec66b325'
WARNING: Error parsing dependencies of lsst-meas-extensions-photometrykron: Invalid version: 'gd8ff7fe66e+2420ccdea7'
WARNING: Error parsing dependencies of lsst-meas-extensions-convolved: Invalid version: 'g7da95dfc27+e751bbf29f'
WARNING: Error parsing dependencies of lsst-ip-isr: Invalid version: 'g6bd32b75b5+2420ccdea7'
WARNING: Error parsing dependencies of lsst-verify-metrics: Invalid version: 'g05f563eca1+fcb1d3bbc8'
WARNING: Error parsing dependencies of lsst-sdm-tools: Invalid version: 'g313cd81ece+1a91586fa4'
WARNING: Error parsing dependencies of lsst-sdm-schemas: Invalid version: 'ge56a158fd1+4dc8b35b08'
WARNING: Error parsing dependencies of lsst-felis: Invalid version: 'g73e563b5c8+e14f1d7a60'
WARNING: Error parsing dependencies of lsst-dax-apdb: Invalid version: 'ga9e4eb89a6+85210110a1'
WARNING: Error parsing dependencies of lsst-verify: Invalid version: 'g1c6cc2e879+5af2f8c6be'
WARNING: Error parsing dependencies of lsst-meas-extensions-shapehsm: Invalid version: 'gfcd60083fb+2420ccdea7'
WARNING: Error parsing dependencies of lsst-meas-extensions-trailedsources: Invalid version: 'g74acd417e5+37fc0c974d'
WARNING: Error parsing dependencies of lsst-meas-astrom: Invalid version: 'g1ebb85f214+2420ccdea7'
WARNING: Error parsing dependencies of lsst-ip-diffim: Invalid version: 'gef3c2e6661+6b480e0fb7'
WARNING: Error parsing dependencies of lsst-coadd-utils: Invalid version: 'g89139ef638+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-pipe-tasks: Invalid version: 'gb0b61e0e8e+1f27f70249'
WARNING: Error parsing dependencies of lsst-shapelet: Invalid version: 'g47891489e3+5c6313fe9a'
WARNING: Error parsing dependencies of lsst-meas-modelfit: Invalid version: 'g97be763408+bba861c665'
WARNING: Error parsing dependencies of astro-metadata-translator: Invalid version: 'g8cbe06beb2+6e13bcb9e9'
WARNING: Error parsing dependencies of lsst-obs-base: Invalid version: 'gdab83eb0e6+5b1a939f4f'
WARNING: Error parsing dependencies of lsst-pipe-base: Invalid version: 'g6f1feb8048+ea09edc8e9'
WARNING: Error parsing dependencies of lsst-daf-relation: Invalid version: 'gfe93c110ed+50e2446c94'
WARNING: Error parsing dependencies of lsst-resources: Invalid version: 'gdd63cb302e+50e2446c94'
WARNING: Error parsing dependencies of lsst-daf-butler: Invalid version: 'g6dd59efbe6+ec144cf465'
WARNING: Error parsing dependencies of lsst-skymap: Invalid version: 'g1fd858c14a+44c57a1f81'
WARNING: Error parsing dependencies of lsst-meas-base: Invalid version: 'g93e38de9ac+5345a64125'
WARNING: Error parsing dependencies of lsst-meas-algorithms: Invalid version: 'g646c943bdb+dbb9921566'
WARNING: Error parsing dependencies of lsst-meas-deblender: Invalid version: 'g262e1987ae+1a7d68eb3b'
Note: you may need to restart the kernel to use updated packages.

In [3]:
IN_COLAB = 'google.colab' in str(get_ipython())
if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
else:
    print('Not running in Colab; using platform/local storage from src/config.py.')

Not running in Colab; using platform/local storage from src/config.py.

In [4]:
from src import config, history

DATA_ROOT = config.HISTORY_DATA_ROOT
MJD_HISTORY_START = config.MJD2_MIN
MJD_HISTORY_CUTOFF = config.MJD2_MAX

print('Ready.')
config.print_config_summary()
print()
print('History store:', DATA_ROOT)
print('Survey data root:', history.survey_data_root(DATA_ROOT))

Ready.
Configuration
=======================================================
  Last Night: MJD 61181.0 - 61182.0  (1.0 days)  [OK]
  Cumulative LSST History: MJD 61095.0 - 61181.0  (86.0 days)  [OK]
  Samples per range : 5000
  Survey mode       : lsst
  LSST-only filter  : ON
  LSST history start: MJD 61095.0
  Tag filter        : none (all alerts)
  Random seed       : 42
  Realtime night    : ON
  ANTARES lookback  : 1 day(s)
  Populated search  : ON
  Search depth      : 5 day(s)
  Chunked ingest    : ON
  Chunk start size  : 1 day(s)
  Chunk min size    : 30 sec
  Chunk split at    : 9,500/10,000 loci
  Parallel shards   : 3
  History backfill  : OFF
  History data root : /project/mdarim/ANTARES_Analysis
  History data set  : lsst_only
  History target    : 100,000 loci/night
  History LC fetch  : ON
  Use stored history: ON

  Ranges are NON-overlapping  (MJD2_MAX=61181.0, MJD1_MIN=61181.0)

History store: /project/mdarim/ANTARES_Analysis
Survey data root: /project/mdarim/ANTARES_Analysis/data/lsst_only

## 1. Tiny Smoke Backfill

This creates one nightly partition with a small target and skips lightcurves. Use it first to verify platform paths, manifests, parquet writing, and resume behavior.

In [5]:
from pathlib import Path

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

print("Using writable DATA_ROOT:", DATA_ROOT)

Using writable DATA_ROOT: /home/mdarim/ANTARES_Analysis_Data

In [7]:
smoke_manifest = history.ingest_night(
    data_root=DATA_ROOT,
    mjd_min=61096.0,
    mjd_max=61096.1,
    target_loci=100,
    fetch_lightcurves=False,
    resume=False,
    range_label="History 2026/2/25 smoke",
    parallel_shards=1,
    max_results_per_chunk=100,
    split_threshold=95,
    lsst_only=True,
    update_indexes=True,
    verbose=True,
)

smoke_manifest

  Chunked query 'History 2026/2/25 smoke'  MJD [61096.000000, 61096.100000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61096.000000-61096.100000    8640.0s     100 loci  split  (live; 2 queued)
       2. 61096.000000-61096.050000    4320.0s     100 loci  split  (live; 3 queued)
       3. 61096.000000-61096.025000    2160.0s     100 loci  split  (live; 4 queued)
       4. 61096.000000-61096.012500    1080.0s       0 loci  accepted  (live; 3 queued)
       5. 61096.012500-61096.025000    1080.0s     100 loci  split  (live; 4 queued)
       6. 61096.012500-61096.018750     540.0s       0 loci  accepted  (live; 3 queued)
       7. 61096.018750-61096.025000     540.0s     100 loci  split  (live; 4 queued)
       8. 61096.018750-61096.021875     270.0s       0 loci  accepted  (live; 3 queued)
       9. 61096.021875-61096.025000     270.0s     100 loci  split  (live; 4 queued)
      10. 61096.021875-61096.023438     135.0s       0 loci  accepted  (live; 3 queued)
      11. 61096.023438-61096.025000     135.0s     100 loci  split  (live; 4 queued)
      12. 61096.023438-61096.024219      67.5s     100 loci  split  (live; 5 queued)
      13. 61096.023438-61096.023828      33.7s      69 loci  accepted  (live; 4 queued)
      14. 61096.023828-61096.024219      33.7s      56 loci  accepted  (live; 3 queued)
    target reached (125/100); stopping with 3 unqueried chunks.
  History 2026/2/25 smoke: 100 unique loci from 6 accepted chunks  (8 splits, 7.8s)
  Lightcurve fetch disabled for this run.

{'manifest': {'date_utc': '2026-02-25',
  'mjd_min': 61096.0,
  'mjd_max': 61096.1,
  'query_tag': None,
  'target_loci': 100,
  'actual_loci': 100,
  'alert_rows': 0,
  'chunk_count': 6,
  'split_count': 8,
  'saturated_chunk_count': 0,
  'status': 'complete',
  'survey_mode': 'lsst',
  'lsst_filter_used': True,
  'lsst_filter': {'bool': {'should': [{'exists': {'field': 'properties.survey.lsst.dia_object_id'}},
     {'exists': {'field': 'properties.survey.lsst.ss_object_id'}}],
    'minimum_should_match': 1}},
  'parallel_shards': 1,
  'lsst_dia_count': 100,
  'lsst_ss_count': 0,
  'ztf_object_id_count': 0,
  'started_at_utc': '2026-05-23T22:04:45+00:00',
  'finished_at_utc': '2026-05-23T22:04:53+00:00',
  'runtime_seconds': 7.9,
  'validation': {'mjd_pass': True,
   'mjd_missing_column': False,
   'mjd_below_count': 0,
   'mjd_above_count': 0,
   'duplicate_locus_count': 0,
   'coordinate_pass': True,
   'coordinate_missing_columns': False,
   'bad_ra_count': 0,
   'bad_dec_count': 0,
   'overlap_count': 0,
   'alert_locus_link_pass': True,
   'alert_rows_without_locus': 0,
   'lsst_only_pass': True,
   'lsst_identifier_count': 100,
   'lsst_dia_count': 100,
   'lsst_ss_count': 0,
   'ztf_object_id_count': 0,
   'history_start_pass': True,
   'append_ready': True},
  'paths': {'loci': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/loci.parquet',
   'alerts': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/alerts.parquet',
   'manifest': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/manifest.json'}},
 'df_loci':                locus_id         ra        dec        tags  num_alerts  \
 0   ANT202604kz894mg8er  60.050159 -47.956908  in_LSSTDDF           1
 1   ANT20260dv0flx55ycb  65.087749 -47.577110  in_LSSTDDF          50
 2   ANT20260m19n2bswqlf  63.137507 -46.219669  in_LSSTDDF          91
 3   ANT20260rq2o7n1gond  59.227386 -49.447132  in_LSSTDDF           7
 4   ANT20260sj11chhyw7o  58.952820 -47.974974  in_LSSTDDF           1
 ..                  ...        ...        ...         ...         ...
 95  ANT2026q0rc849p4ak1  62.266519 -46.218466  in_LSSTDDF          14
 96  ANT2026q9ysamxwy4xw  61.664202 -46.188367                       2
 97  ANT2026qmh5vxqrysli  58.107180 -48.859764  in_LSSTDDF           1
 98  ANT2026r08l46ao6229  62.045751 -48.821668  in_LSSTDDF           1
 99  ANT2026s0hko7h9ui29  59.100095 -47.545439                       1

     num_mag_values       brightest_alert_id  brightest_alert_magnitude  \
 0                1  lsst:170054916267049108                  23.671716
 1               50  lsst:170054916365090984                  21.850260
 2               91  lsst:170028492712312986                  22.738133
 3                7  lsst:170032890709016602                  22.626314
 4                1  lsst:170054916287496225                  23.741801
 ..             ...                      ...                        ...
 95              14  lsst:170050474614980700                  22.894791
 96               2  lsst:170054916421190522                  22.551196
 97               1  lsst:170054916249223273                  22.596383
 98               1  lsst:170054916232970295                  22.931237
 99               1  lsst:170054916285399233                  23.606282

     brightest_alert_observation_time          newest_alert_id  ...  \
 0                       61096.023493  lsst:170054916267049108  ...
 1                       61096.023924  lsst:170054916365090984  ...
 2                       61090.077709  lsst:170054916414374086  ...
 3                       61091.100586  lsst:170054916224581754  ...
 4                       61096.023493  lsst:170054916287496225  ...
 ..                               ...                      ...  ...
 95                      61095.048220  lsst:170054916420141117  ...
 96                      61096.023924  lsst:170054916421190522  ...
 97                      61096.023493  lsst:170054916249223273  ...
 98                      61096.023493  lsst:170054916232970295  ...
 99                      61096.023493  lsst:170054916285399233  ...

             oldest_alert_id  oldest_alert_magnitude  \
 0   lsst:170054916267049108               23.671716
 1   lsst:170028486749061212               23.318752
 2   lsst:313708289159331849               23.737302
 3   lsst:170028486623232132               23.388808
 4   lsst:170054916287496225               23.741801
 ..                      ...                     ...
 95  lsst:170028485732466721               23.374747
 96  lsst:170050471535313371               22.614555
 97  lsst:170054916249223273               22.596383
 98  lsst:170054916232970295               22.931237
 99  lsst:170054916285399233               23.606282

    oldest_alert_observation_time  is_corrected  \
 0                   61096.023493          true
 1                   61090.055275          true
 2                   60991.259038          true
 3                   61090.054840          true
 4                   61096.023493          true
 ..                           ...           ...
 95                  61090.047584          true
 96                  61095.023438          true
 97                  61096.023493          true
 98                  61096.023493          true
 99                  61096.023493          true

                                                survey night_date_utc  \
 0   {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 1   {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 2   {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 3   {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 4   {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 ..                                                ...            ...
 95  {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 96  {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 97  {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 98  {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25
 99  {'ztf': {'id': [], 'rcid': [], 'field': [], 's...     2026-02-25

    night_mjd_min night_mjd_max            ingested_at_utc  source_query_mode
 0        61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 1        61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 2        61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 3        61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 4        61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 ..           ...           ...                        ...                ...
 95       61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 96       61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 97       61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 98       61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked
 99       61096.0       61096.1  2026-05-23T22:04:52+00:00   adaptive_chunked

 [100 rows x 22 columns],
 'df_alerts': Empty DataFrame
 Columns: [locus_id, night_date_utc, range_label]
 Index: [],
 'report':                       label       mjd_min       mjd_max  width_seconds  \
 0   History 2026/2/25 smoke  61096.000000  61096.100000    8640.000000
 1   History 2026/2/25 smoke  61096.000000  61096.050000    4320.000000
 2   History 2026/2/25 smoke  61096.000000  61096.025000    2160.000000
 3   History 2026/2/25 smoke  61096.000000  61096.012500    1080.000000
 4   History 2026/2/25 smoke  61096.012500  61096.025000    1080.000000
 5   History 2026/2/25 smoke  61096.012500  61096.018750     540.000001
 6   History 2026/2/25 smoke  61096.018750  61096.025000     540.000000
 7   History 2026/2/25 smoke  61096.018750  61096.021875     270.000000
 8   History 2026/2/25 smoke  61096.021875  61096.025000     270.000000
 9   History 2026/2/25 smoke  61096.021875  61096.023438     134.999999
 10  History 2026/2/25 smoke  61096.023438  61096.025000     135.000000
 11  History 2026/2/25 smoke  61096.023438  61096.024219      67.500000
 12  History 2026/2/25 smoke  61096.023438  61096.023828      33.750000
 13  History 2026/2/25 smoke  61096.023828  61096.024219      33.750000

     n_loci    status source  include_upper
 0      100     split   live           True
 1      100     split   live          False
 2      100     split   live          False
 3        0  accepted   live          False
 4      100     split   live          False
 5        0  accepted   live          False
 6      100     split   live          False
 7        0  accepted   live          False
 8      100     split   live          False
 9        0  accepted   live          False
 10     100     split   live          False
 11     100     split   live          False
 12      69  accepted   live          False
 13      56  accepted   live          False  ,
 'skipped': False}

In [8]:
loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("Cumulative loci rows:", len(loci_index))
display(nightly_summary.tail())

Cumulative loci rows: 100

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
0,2026-02-24,2026/2/24,61095.0,61096.0,None,1000,0,0,0,0,...,0,0,None,None,112.07,2026-05-11T23:05:28+00:00,2026-05-11T23:07:20+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
1,2026-02-25,2026/2/25,61096.0,61096.1,None,100,100,0,6,8,...,0,0,True,True,7.90,2026-05-23T22:04:45+00:00,2026-05-23T22:04:53+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...

In [9]:
test_manifest = history.ingest_night(
    data_root=DATA_ROOT,
    mjd_min=61096.0,
    mjd_max=61096.25,
    target_loci=1000,
    fetch_lightcurves=False,
    resume=False,
    range_label="History 2026/2/25 quarter-night test",
    parallel_shards=1,
    max_results_per_chunk=500,
    split_threshold=475,
    lsst_only=True,
    update_indexes=True,
    verbose=True,
)

test_manifest["manifest"]

  Chunked query 'History 2026/2/25 quarter-night test'  MJD [61096.000000, 61096.250000]
    ES limit=500, split at >= 475, minimum chunk=30s
       1. 61096.000000-61096.250000   21600.0s     500 loci  split  (live; 2 queued)
       2. 61096.000000-61096.125000   10800.0s     500 loci  split  (live; 3 queued)
       3. 61096.000000-61096.062500    5400.0s     500 loci  split  (live; 4 queued)
       4. 61096.000000-61096.031250    2700.0s     500 loci  split  (live; 5 queued)
       5. 61096.000000-61096.015625    1350.0s       0 loci  accepted  (live; 4 queued)
       6. 61096.015625-61096.031250    1350.0s     500 loci  split  (live; 5 queued)
       7. 61096.015625-61096.023438     675.0s       0 loci  accepted  (live; 4 queued)
       8. 61096.023438-61096.031250     675.0s     500 loci  split  (live; 5 queued)
       9. 61096.023438-61096.027344     337.5s     500 loci  split  (live; 6 queued)
      10. 61096.023438-61096.025391     168.8s     311 loci  accepted  (live; 5 queued)
      11. 61096.025391-61096.027344     168.8s     297 loci  accepted  (live; 4 queued)
      12. 61096.027344-61096.031250     337.5s     500 loci  split  (live; 5 queued)
      13. 61096.027344-61096.029297     168.8s     294 loci  accepted  (live; 4 queued)
      14. 61096.029297-61096.031250     168.8s     221 loci  accepted  (live; 3 queued)
    target reached (1,116/1,000); stopping with 3 unqueried chunks.
  History 2026/2/25 quarter-night test: 1,000 unique loci from 6 accepted chunks  (8 splits, 41.5s)
  Lightcurve fetch disabled for this run.

{'date_utc': '2026-02-25',
 'mjd_min': 61096.0,
 'mjd_max': 61096.25,
 'query_tag': None,
 'target_loci': 1000,
 'actual_loci': 1000,
 'alert_rows': 0,
 'chunk_count': 6,
 'split_count': 8,
 'saturated_chunk_count': 0,
 'status': 'complete',
 'survey_mode': 'lsst',
 'lsst_filter_used': True,
 'lsst_filter': {'bool': {'should': [{'exists': {'field': 'properties.survey.lsst.dia_object_id'}},
    {'exists': {'field': 'properties.survey.lsst.ss_object_id'}}],
   'minimum_should_match': 1}},
 'parallel_shards': 1,
 'lsst_dia_count': 1000,
 'lsst_ss_count': 0,
 'ztf_object_id_count': 0,
 'started_at_utc': '2026-05-23T22:05:01+00:00',
 'finished_at_utc': '2026-05-23T22:05:42+00:00',
 'runtime_seconds': 41.5,
 'validation': {'mjd_pass': True,
  'mjd_missing_column': False,
  'mjd_below_count': 0,
  'mjd_above_count': 0,
  'duplicate_locus_count': 0,
  'coordinate_pass': True,
  'coordinate_missing_columns': False,
  'bad_ra_count': 0,
  'bad_dec_count': 0,
  'overlap_count': 0,
  'alert_locus_link_pass': True,
  'alert_rows_without_locus': 0,
  'lsst_only_pass': True,
  'lsst_identifier_count': 1000,
  'lsst_dia_count': 1000,
  'lsst_ss_count': 0,
  'ztf_object_id_count': 0,
  'history_start_pass': True,
  'append_ready': True},
 'paths': {'loci': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/loci.parquet',
  'alerts': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/alerts.parquet',
  'manifest': '/home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/manifest.json'}}

In [ ]:
loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("Cumulative loci rows:", len(loci_index))
display(nightly_summary.tail())

In [ ]:
half_manifest = history.ingest_night(
    data_root=DATA_ROOT,
    mjd_min=61096.0,
    mjd_max=61096.5,
    target_loci=5000,
    fetch_lightcurves=False,
    resume=False,
    range_label="History 2026/2/25 half-night test",
    parallel_shards=1,
    max_results_per_chunk=1000,
    split_threshold=950,
    lsst_only=True,
    update_indexes=True,
    verbose=True,
)

half_manifest["manifest"]

In [ ]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data_Clean")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

night_ranges = [
    (61095.0, 61096.0, "2026/2/24"),
    (61096.0, 61097.0, "2026/2/25"),
    (61097.0, 61098.0, "2026/2/26"),
    (61098.0, 61099.0, "2026/2/27"),
    (61099.0, 61100.0, "2026/2/28"),
]

for lo, hi, label in night_ranges:
    print("\n" + "=" * 72)
    print(f"Running LSST-only ANTARES backfill for {label}")

    result = history.ingest_night(
        data_root=DATA_ROOT,
        mjd_min=lo,
        mjd_max=hi,
        target_loci=1000,
        fetch_lightcurves=False,
        resume=True,
        range_label=f"History {label}",
        parallel_shards=1,
        max_results_per_chunk=500,
        split_threshold=475,
        lsst_only=True,
        update_indexes=True,
        verbose=True,
    )

    print(result["manifest"]["status"], result["manifest"]["actual_loci"])

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("\nDONE")
print("DATA_ROOT:", DATA_ROOT)
print("Cumulative LSST-only loci rows:", len(loci_index))
display(nightly_summary.tail(10))

In [ ]:
resume_summary = history.backfill_history(
    data_root=DATA_ROOT,
    mjd_start=MJD_HISTORY_START,
    mjd_stop=MJD_HISTORY_START + 1,
    target_loci=1000,
    max_nights=1,
    fetch_lightcurves=False,
    resume=True,
        parallel_shards=config.CHUNK_PARALLEL_SHARDS,
        lsst_only=config.LSST_ONLY,
)
display(resume_summary.tail())

## 2. Three-Night Test

Turn this on after the smoke test. It checks multi-night folder layout and cumulative-index behavior.

In [ ]:
RUN_THREE_NIGHT_TEST = False

if RUN_THREE_NIGHT_TEST:
    three_night_summary = history.backfill_history(
        data_root=DATA_ROOT,
        mjd_start=MJD_HISTORY_START,
        mjd_stop=MJD_HISTORY_START + 3,
        target_loci=5000,
        max_nights=3,
        fetch_lightcurves=False,
        resume=True,
        parallel_shards=config.CHUNK_PARALLEL_SHARDS,
        lsst_only=config.LSST_ONLY,
    )
    display(three_night_summary.tail(10))

## 3. Full-Scale Runs

Run one full night first. Only then turn on the full historical backfill.

In [12]:
import requests
import time

url = "https://api.antares.noirlab.edu/v1/loci"

for i in range(5):
    print("Test", i + 1)
    try:
        r = requests.get(url, timeout=20)
        print("status:", r.status_code, "seconds ok")
    except Exception as e:
        print("FAILED:", type(e).__name__, e)
    time.sleep(5)

Test 1
status: 200 seconds ok
Test 2
status: 200 seconds ok
Test 3
status: 200 seconds ok
Test 4
status: 200 seconds ok
Test 5
status: 200 seconds ok

In [13]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data_Clean")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

test = history.ingest_night(
    data_root=DATA_ROOT,
    mjd_min=61096.0,
    mjd_max=61096.1,
    target_loci=100,
    fetch_lightcurves=False,
    resume=True,
    range_label="History 2026/2/25 smoke",
    parallel_shards=1,
    max_results_per_chunk=100,
    split_threshold=95,
    lsst_only=True,
    update_indexes=True,
    verbose=True,
)

test["manifest"]

  Chunked query 'History 2026/2/25 smoke'  MJD [61096.000000, 61096.100000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61096.000000-61096.100000    8640.0s     100 loci  split  (live; 2 queued)
       2. 61096.000000-61096.050000    4320.0s     100 loci  split  (live; 3 queued)
       3. 61096.000000-61096.025000    2160.0s     100 loci  split  (live; 4 queued)
       4. 61096.000000-61096.012500    1080.0s       0 loci  accepted  (live; 3 queued)
       5. 61096.012500-61096.025000    1080.0s     100 loci  split  (live; 4 queued)
       6. 61096.012500-61096.018750     540.0s       0 loci  accepted  (live; 3 queued)
       7. 61096.018750-61096.025000     540.0s     100 loci  split  (live; 4 queued)
       8. 61096.018750-61096.021875     270.0s       0 loci  accepted  (live; 3 queued)
       9. 61096.021875-61096.025000     270.0s     100 loci  split  (live; 4 queued)
      10. 61096.021875-61096.023438     135.0s       0 loci  accepted  (live; 3 queued)
      11. 61096.023438-61096.025000     135.0s     100 loci  split  (live; 4 queued)
      12. 61096.023438-61096.024219      67.5s     100 loci  split  (live; 5 queued)
      13. 61096.023438-61096.023828      33.7s      69 loci  accepted  (live; 4 queued)
      14. 61096.023828-61096.024219      33.7s      56 loci  accepted  (live; 3 queued)
    target reached (125/100); stopping with 3 unqueried chunks.
  History 2026/2/25 smoke: 100 unique loci from 6 accepted chunks  (8 splits, 7.3s)
  Lightcurve fetch disabled for this run.

{'date_utc': '2026-02-25',
 'mjd_min': 61096.0,
 'mjd_max': 61096.1,
 'query_tag': None,
 'target_loci': 100,
 'actual_loci': 100,
 'alert_rows': 0,
 'chunk_count': 6,
 'split_count': 8,
 'saturated_chunk_count': 0,
 'status': 'complete',
 'survey_mode': 'lsst',
 'lsst_filter_used': True,
 'lsst_filter': {'bool': {'should': [{'exists': {'field': 'properties.survey.lsst.dia_object_id'}},
    {'exists': {'field': 'properties.survey.lsst.ss_object_id'}}],
   'minimum_should_match': 1}},
 'parallel_shards': 1,
 'lsst_dia_count': 100,
 'lsst_ss_count': 0,
 'ztf_object_id_count': 0,
 'started_at_utc': '2026-05-23T22:20:39+00:00',
 'finished_at_utc': '2026-05-23T22:20:47+00:00',
 'runtime_seconds': 7.34,
 'validation': {'mjd_pass': True,
  'mjd_missing_column': False,
  'mjd_below_count': 0,
  'mjd_above_count': 0,
  'duplicate_locus_count': 0,
  'coordinate_pass': True,
  'coordinate_missing_columns': False,
  'bad_ra_count': 0,
  'bad_dec_count': 0,
  'overlap_count': 0,
  'alert_locus_link_pass': True,
  'alert_rows_without_locus': 0,
  'lsst_only_pass': True,
  'lsst_identifier_count': 100,
  'lsst_dia_count': 100,
  'lsst_ss_count': 0,
  'ztf_object_id_count': 0,
  'history_start_pass': True,
  'append_ready': True},
 'paths': {'loci': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/loci.parquet',
  'alerts': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/alerts.parquet',
  'manifest': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/manifest.json'}}

In [11]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data_Clean")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

night_ranges = [
    (61095.0, 61096.0, "2026/2/24"),
    (61096.0, 61097.0, "2026/2/25"),
    (61097.0, 61098.0, "2026/2/26"),
    (61098.0, 61099.0, "2026/2/27"),
    (61099.0, 61100.0, "2026/2/28"),
]

for lo, hi, label in night_ranges:
    print("\n" + "=" * 72)
    print(f"Running LSST-only ANTARES backfill for {label}")

    result = history.ingest_night(
        data_root=DATA_ROOT,
        mjd_min=lo,
        mjd_max=hi,
        target_loci=1000,
        fetch_lightcurves=False,
        resume=True,
        range_label=f"History {label}",
        parallel_shards=1,
        max_results_per_chunk=500,
        split_threshold=475,
        lsst_only=True,
        update_indexes=True,
        verbose=True,
    )

    print(result["manifest"]["date_utc"], result["manifest"]["status"], result["manifest"]["actual_loci"])

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("\nDONE")
print("DATA_ROOT:", DATA_ROOT)
print("Cumulative LSST-only loci rows:", len(loci_index))
display(nightly_summary.tail(10))

========================================================================
Running LSST-only ANTARES backfill for 2026/2/24
  Chunked query 'History 2026/2/24'  MJD [61095.000000, 61096.000000]
    ES limit=500, split at >= 475, minimum chunk=30s
       1. 61095.000000-61096.000000   86400.0s     500 loci  split  (live; 2 queued)
       2. 61095.000000-61095.500000   43200.0s     500 loci  split  (live; 3 queued)
       3. 61095.000000-61095.250000   21600.0s     500 loci  split  (live; 4 queued)
       4. 61095.000000-61095.125000   10800.0s     500 loci  split  (live; 5 queued)
       5. 61095.000000-61095.062500    5400.0s     500 loci  split  (live; 6 queued)
       6. 61095.000000-61095.031250    2700.0s     500 loci  split  (live; 7 queued)
       7. 61095.000000-61095.015625    1350.0s       0 loci  accepted  (live; 6 queued)
       8. 61095.015625-61095.031250    1350.0s     500 loci  split  (live; 7 queued)
       9. 61095.015625-61095.023438     675.0s     482 loci  split  (live; 8 queued)
      10. 61095.015625-61095.019531     337.5s       0 loci  accepted  (live; 7 queued)
      11. 61095.019531-61095.023438     337.5s     482 loci  split  (live; 8 queued)
      12. 61095.019531-61095.021484     168.8s       0 loci  accepted  (live; 7 queued)
  [ERROR] Chunk query failed for 61095.021484-61095.023438: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.021484375%2C+%22lt%22%3A+61095.0234375%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=160&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf970759b20>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
  [ERROR] Nightly ingest failed for 2026-02-24: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.021484375%2C+%22lt%22%3A+61095.0234375%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=160&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf970759b20>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))

ConnectTimeout: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.021484375%2C+%22lt%22%3A+61095.0234375%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=160&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf970759b20>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))

In [14]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data_Clean")
DATA_ROOT.mkdir(parents=True, exist_ok=True)

single = history.ingest_night(
    data_root=DATA_ROOT,
    mjd_min=61096.0,
    mjd_max=61097.0,
    target_loci=1000,
    fetch_lightcurves=False,
    resume=True,
    range_label="History 2026/2/25 single-night 1000",
    parallel_shards=1,
    max_results_per_chunk=100,
    split_threshold=95,
    lsst_only=True,
    update_indexes=True,
    verbose=True,
)

single["manifest"]

  Resume: found 2026-02-25; loading existing nightly partition.

{'actual_loci': 100,
 'alert_rows': 0,
 'chunk_count': 6,
 'date_utc': '2026-02-25',
 'finished_at_utc': '2026-05-23T22:20:47+00:00',
 'lsst_dia_count': 100,
 'lsst_filter': {'bool': {'minimum_should_match': 1,
   'should': [{'exists': {'field': 'properties.survey.lsst.dia_object_id'}},
    {'exists': {'field': 'properties.survey.lsst.ss_object_id'}}]}},
 'lsst_filter_used': True,
 'lsst_ss_count': 0,
 'mjd_max': 61096.1,
 'mjd_min': 61096.0,
 'parallel_shards': 1,
 'paths': {'alerts': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/alerts.parquet',
  'loci': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/loci.parquet',
  'manifest': '/home/mdarim/ANTARES_Analysis_Data_Clean/data/lsst_only/nightly/2026/02/25/manifest.json'},
 'query_tag': None,
 'runtime_seconds': 7.34,
 'saturated_chunk_count': 0,
 'split_count': 8,
 'started_at_utc': '2026-05-23T22:20:39+00:00',
 'status': 'complete',
 'survey_mode': 'lsst',
 'target_loci': 100,
 'validation': {'alert_locus_link_pass': True,
  'alert_rows_without_locus': 0,
  'append_ready': True,
  'bad_dec_count': 0,
  'bad_ra_count': 0,
  'coordinate_missing_columns': False,
  'coordinate_pass': True,
  'duplicate_locus_count': 0,
  'history_start_pass': True,
  'lsst_dia_count': 100,
  'lsst_identifier_count': 100,
  'lsst_only_pass': True,
  'lsst_ss_count': 0,
  'mjd_above_count': 0,
  'mjd_below_count': 0,
  'mjd_missing_column': False,
  'mjd_pass': True,
  'overlap_count': 0,
  'ztf_object_id_count': 0},
 'ztf_object_id_count': 0}

In [18]:
from pathlib import Path
import time
import pandas as pd

from src import history


def backfill_range(
    data_root,
    mjd_start,
    mjd_stop,
    target_loci_per_night=1000,
    fetch_lightcurves=False,
    lsst_only=True,
    parallel_shards=1,
    max_retries=5,
    retry_sleep_seconds=(30, 90, 180, 300, 600),
    max_results_per_chunk=100,
    split_threshold=95,
    update_indexes_each_night=False,
    verbose=True,
):
    data_root = Path(data_root)
    data_root.mkdir(parents=True, exist_ok=True)

    chunk_cache_dir = data_root / "cache" / "chunks"
    chunk_cache_dir.mkdir(parents=True, exist_ok=True)

    manifests = []
    failures = []

    for date_utc, lo, hi in history.iter_night_windows(mjd_start, mjd_stop):
        label_display = history.display_date(date_utc)
        range_label = f"History {label_display}"

        print("\n" + "=" * 72)
        print(f"Backfilling {label_display}  MJD [{lo}, {hi}]")

        success = False
        last_error = None

        for attempt in range(1, max_retries + 1):
            print(f"\nAttempt {attempt}/{max_retries} for {label_display}")

            try:
                result = history.ingest_night(
                    data_root=data_root,
                    mjd_min=lo,
                    mjd_max=hi,
                    target_loci=target_loci_per_night,
                    fetch_lightcurves=fetch_lightcurves,
                    resume=True,
                    range_label=range_label,
                    chunk_cache_dir=chunk_cache_dir,
                    parallel_shards=parallel_shards,
                    max_results_per_chunk=max_results_per_chunk,
                    split_threshold=split_threshold,
                    lsst_only=lsst_only,
                    update_indexes=update_indexes_each_night,
                    verbose=verbose,
                )

                manifest = result["manifest"]
                manifests.append(manifest)

                print(
                    f"\nSUCCESS {label_display}: "
                    f"{manifest['status']}  actual_loci={manifest['actual_loci']}"
                )

                success = True
                break

            except Exception as exc:
                last_error = str(exc)
                print(f"\nFAILED attempt {attempt}/{max_retries} for {label_display}")
                print(last_error)

                if attempt < max_retries:
                    sleep_for = retry_sleep_seconds[min(attempt - 1, len(retry_sleep_seconds) - 1)]
                    print(f"Sleeping {sleep_for} seconds before retry...")
                    time.sleep(sleep_for)

        if not success:
            failures.append(
                {
                    "date_utc": date_utc,
                    "display_date": label_display,
                    "mjd_min": lo,
                    "mjd_max": hi,
                    "error": last_error,
                }
            )

    loci_index, nightly_summary = history.update_cumulative_indexes(data_root)

    print("\n" + "=" * 72)
    print("BACKFILL FINISHED")
    print("Successful night attempts:", len(manifests))
    print("Failed nights:", len(failures))
    print("Cumulative loci rows:", len(loci_index))

    return {
        "manifests": manifests,
        "failures": failures,
        "loci_index": loci_index,
        "nightly_summary": nightly_summary,
    }

In [19]:
result = backfill_range(
    data_root=Path("/home/mdarim/ANTARES_Analysis_Data"),
    mjd_start=61095.0,
    mjd_stop=61100.0,
    target_loci_per_night=1000,
    fetch_lightcurves=False,
    lsst_only=True,
    parallel_shards=1,
    max_retries=5,
    max_results_per_chunk=100,
    split_threshold=95,
    update_indexes_each_night=False,
    verbose=True,
)

display(result["nightly_summary"])
result["failures"]

========================================================================
Backfilling 2026/2/24  MJD [61095.0, 61096.0]

Attempt 1/5 for 2026/2/24
  Chunked query 'History 2026/2/24'  MJD [61095.000000, 61096.000000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61095.000000-61096.000000   86400.0s     100 loci  split  (live; 2 queued)
       2. 61095.000000-61095.500000   43200.0s     100 loci  split  (live; 3 queued)
       3. 61095.000000-61095.250000   21600.0s     100 loci  split  (live; 4 queued)
       4. 61095.000000-61095.125000   10800.0s     100 loci  split  (live; 5 queued)
       5. 61095.000000-61095.062500    5400.0s     100 loci  split  (live; 6 queued)
       6. 61095.000000-61095.031250    2700.0s     100 loci  split  (live; 7 queued)
       7. 61095.000000-61095.015625    1350.0s       0 loci  accepted  (live; 6 queued)
       8. 61095.015625-61095.031250    1350.0s     100 loci  split  (live; 7 queued)
       9. 61095.015625-61095.023438     675.0s     100 loci  split  (live; 8 queued)
      10. 61095.015625-61095.019531     337.5s       0 loci  accepted  (live; 7 queued)
      11. 61095.019531-61095.023438     337.5s     100 loci  split  (live; 8 queued)
      12. 61095.019531-61095.021484     168.8s       0 loci  accepted  (live; 7 queued)
      13. 61095.021484-61095.023438     168.8s     100 loci  split  (live; 8 queued)
      14. 61095.021484-61095.022461      84.4s       0 loci  accepted  (live; 7 queued)
      15. 61095.022461-61095.023438      84.4s     100 loci  split  (live; 8 queued)
      16. 61095.022461-61095.022949      42.2s       0 loci  accepted  (live; 7 queued)
      17. 61095.022949-61095.023438      42.2s     100 loci  split  (live; 8 queued)
      18. 61095.022949-61095.023193      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      19. 61095.023193-61095.023438      21.1s       0 loci  accepted  (live; 6 queued)
      20. 61095.023438-61095.031250     675.0s     100 loci  split  (live; 7 queued)
      21. 61095.023438-61095.027344     337.5s     100 loci  split  (live; 8 queued)
      22. 61095.023438-61095.025391     168.8s     100 loci  split  (live; 9 queued)
      23. 61095.023438-61095.024414      84.4s     100 loci  split  (live; 10 queued)
      24. 61095.023438-61095.023926      42.2s     100 loci  split  (live; 11 queued)
      25. 61095.023438-61095.023682      21.1s     100 loci  accepted_at_minimum_saturated  (live; 10 queued)
      26. 61095.023682-61095.023926      21.1s     100 loci  accepted_at_minimum_saturated  (live; 9 queued)
      27. 61095.023926-61095.024414      42.2s     100 loci  split  (live; 10 queued)
      28. 61095.023926-61095.024170      21.1s       0 loci  accepted  (live; 9 queued)
      29. 61095.024170-61095.024414      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      30. 61095.024414-61095.025391      84.4s     100 loci  split  (live; 9 queued)
      31. 61095.024414-61095.024902      42.2s     100 loci  split  (live; 10 queued)
      32. 61095.024414-61095.024658      21.1s       0 loci  accepted  (live; 9 queued)
      33. 61095.024658-61095.024902      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      34. 61095.024902-61095.025391      42.2s     100 loci  split  (live; 9 queued)
      35. 61095.024902-61095.025146      21.1s       0 loci  accepted  (live; 8 queued)
      36. 61095.025146-61095.025391      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      37. 61095.025391-61095.027344     168.8s     100 loci  split  (live; 8 queued)
      38. 61095.025391-61095.026367      84.4s     100 loci  split  (live; 9 queued)
      39. 61095.025391-61095.025879      42.2s     100 loci  split  (live; 10 queued)
      40. 61095.025391-61095.025635      21.1s     100 loci  accepted_at_minimum_saturated  (live; 9 queued)
      41. 61095.025635-61095.025879      21.1s       0 loci  accepted  (live; 8 queued)
      42. 61095.025879-61095.026367      42.2s       0 loci  accepted  (live; 7 queued)
      43. 61095.026367-61095.027344      84.4s       0 loci  accepted  (live; 6 queued)
      44. 61095.027344-61095.031250     337.5s       0 loci  accepted  (live; 5 queued)
      45. 61095.031250-61095.062500    2700.0s     100 loci  split  (live; 6 queued)
      46. 61095.031250-61095.046875    1350.0s     100 loci  split  (live; 7 queued)
      47. 61095.031250-61095.039062     675.0s       0 loci  accepted  (live; 6 queued)
      48. 61095.039062-61095.046875     675.0s     100 loci  split  (live; 7 queued)
      49. 61095.039062-61095.042969     337.5s     100 loci  split  (live; 8 queued)
      50. 61095.039062-61095.041016     168.8s       0 loci  accepted  (live; 7 queued)
      51. 61095.041016-61095.042969     168.8s     100 loci  split  (live; 8 queued)
      52. 61095.041016-61095.041992      84.4s     100 loci  split  (live; 9 queued)
      53. 61095.041016-61095.041504      42.2s       0 loci  accepted  (live; 8 queued)
      54. 61095.041504-61095.041992      42.2s     100 loci  split  (live; 9 queued)
      55. 61095.041504-61095.041748      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      56. 61095.041748-61095.041992      21.1s       0 loci  accepted  (live; 7 queued)
      57. 61095.041992-61095.042969      84.4s     100 loci  split  (live; 8 queued)
      58. 61095.041992-61095.042480      42.2s     100 loci  split  (live; 9 queued)
      59. 61095.041992-61095.042236      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      60. 61095.042236-61095.042480      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
    target reached (1,000/1,000); stopping with 7 unqueried chunks.
  History 2026/2/24: 1,000 unique loci from 27 accepted chunks  (33 splits, 37.2s)
  [WARN] 10 minimum-size chunks still reached the result cap. Use smaller chunks or add another partition such as RA slices.
  Lightcurve fetch disabled for this run.

SUCCESS 2026/2/24: saturated_unresolved  actual_loci=1000

========================================================================
Backfilling 2026/2/25  MJD [61096.0, 61097.0]

Attempt 1/5 for 2026/2/25
  Resume: found 2026-02-25; loading existing nightly partition.

SUCCESS 2026/2/25: complete  actual_loci=1000

========================================================================
Backfilling 2026/2/26  MJD [61097.0, 61098.0]

Attempt 1/5 for 2026/2/26
  Chunked query 'History 2026/2/26'  MJD [61097.000000, 61098.000000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61097.000000-61098.000000   86400.0s     100 loci  split  (live; 2 queued)
       2. 61097.000000-61097.500000   43200.0s     100 loci  split  (live; 3 queued)
       3. 61097.000000-61097.250000   21600.0s     100 loci  split  (live; 4 queued)
       4. 61097.000000-61097.125000   10800.0s     100 loci  split  (live; 5 queued)
       5. 61097.000000-61097.062500    5400.0s       0 loci  accepted  (live; 4 queued)
       6. 61097.062500-61097.125000    5400.0s     100 loci  split  (live; 5 queued)
       7. 61097.062500-61097.093750    2700.0s       0 loci  accepted  (live; 4 queued)
       8. 61097.093750-61097.125000    2700.0s     100 loci  split  (live; 5 queued)
       9. 61097.093750-61097.109375    1350.0s       0 loci  accepted  (live; 4 queued)
      10. 61097.109375-61097.125000    1350.0s     100 loci  split  (live; 5 queued)
      11. 61097.109375-61097.117188     675.0s     100 loci  split  (live; 6 queued)
      12. 61097.109375-61097.113281     337.5s       0 loci  accepted  (live; 5 queued)
      13. 61097.113281-61097.117188     337.5s     100 loci  split  (live; 6 queued)
      14. 61097.113281-61097.115234     168.8s       0 loci  accepted  (live; 5 queued)
      15. 61097.115234-61097.117188     168.8s     100 loci  split  (live; 6 queued)
      16. 61097.115234-61097.116211      84.4s       0 loci  accepted  (live; 5 queued)
      17. 61097.116211-61097.117188      84.4s     100 loci  split  (live; 6 queued)
      18. 61097.116211-61097.116699      42.2s      63 loci  accepted  (live; 5 queued)
      19. 61097.116699-61097.117188      42.2s      69 loci  accepted  (live; 4 queued)
      20. 61097.117188-61097.125000     675.0s     100 loci  split  (live; 5 queued)
      21. 61097.117188-61097.121094     337.5s     100 loci  split  (live; 6 queued)
      22. 61097.117188-61097.119141     168.8s     100 loci  split  (live; 7 queued)
      23. 61097.117188-61097.118164      84.4s     100 loci  split  (live; 8 queued)
      24. 61097.117188-61097.117676      42.2s      76 loci  accepted  (live; 7 queued)
      25. 61097.117676-61097.118164      42.2s      61 loci  accepted  (live; 6 queued)
      26. 61097.118164-61097.119141      84.4s     100 loci  split  (live; 7 queued)
      27. 61097.118164-61097.118652      42.2s      82 loci  accepted  (live; 6 queued)
      28. 61097.118652-61097.119141      42.2s     100 loci  split  (live; 7 queued)
      29. 61097.118652-61097.118896      21.1s     100 loci  accepted_at_minimum_saturated  (live; 6 queued)
      30. 61097.118896-61097.119141      21.1s       0 loci  accepted  (live; 5 queued)
      31. 61097.119141-61097.121094     168.8s     100 loci  split  (live; 6 queued)
      32. 61097.119141-61097.120117      84.4s     100 loci  split  (live; 7 queued)
      33. 61097.119141-61097.119629      42.2s     100 loci  split  (live; 8 queued)
      34. 61097.119141-61097.119385      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      35. 61097.119385-61097.119629      21.1s     100 loci  accepted_at_minimum_saturated  (live; 6 queued)
      36. 61097.119629-61097.120117      42.2s     100 loci  split  (live; 7 queued)
      37. 61097.119629-61097.119873      21.1s       0 loci  accepted  (live; 6 queued)
      38. 61097.119873-61097.120117      21.1s     100 loci  accepted_at_minimum_saturated  (live; 5 queued)
      39. 61097.120117-61097.121094      84.4s     100 loci  split  (live; 6 queued)
      40. 61097.120117-61097.120605      42.2s      94 loci  accepted  (live; 5 queued)
      41. 61097.120605-61097.121094      42.2s      81 loci  accepted  (live; 4 queued)
      42. 61097.121094-61097.125000     337.5s     100 loci  split  (live; 5 queued)
      43. 61097.121094-61097.123047     168.8s     100 loci  split  (live; 6 queued)
      44. 61097.121094-61097.122070      84.4s     100 loci  split  (live; 7 queued)
      45. 61097.121094-61097.121582      42.2s      89 loci  accepted  (live; 6 queued)
    target reached (1,009/1,000); stopping with 6 unqueried chunks.
  History 2026/2/26: 1,000 unique loci from 20 accepted chunks  (25 splits, 37.4s)
  [WARN] 4 minimum-size chunks still reached the result cap. Use smaller chunks or add another partition such as RA slices.
  Lightcurve fetch disabled for this run.

SUCCESS 2026/2/26: saturated_unresolved  actual_loci=1000

========================================================================
Backfilling 2026/2/27  MJD [61098.0, 61099.0]

Attempt 1/5 for 2026/2/27
  Chunked query 'History 2026/2/27'  MJD [61098.000000, 61099.000000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61098.000000-61099.000000   86400.0s     100 loci  split  (live; 2 queued)
       2. 61098.000000-61098.500000   43200.0s     100 loci  split  (live; 3 queued)
       3. 61098.000000-61098.250000   21600.0s     100 loci  split  (live; 4 queued)
       4. 61098.000000-61098.125000   10800.0s     100 loci  split  (live; 5 queued)
       5. 61098.000000-61098.062500    5400.0s     100 loci  split  (live; 6 queued)
       6. 61098.000000-61098.031250    2700.0s     100 loci  split  (live; 7 queued)
       7. 61098.000000-61098.015625    1350.0s       0 loci  accepted  (live; 6 queued)
       8. 61098.015625-61098.031250    1350.0s     100 loci  split  (live; 7 queued)
       9. 61098.015625-61098.023438     675.0s     100 loci  split  (live; 8 queued)
      10. 61098.015625-61098.019531     337.5s       0 loci  accepted  (live; 7 queued)
      11. 61098.019531-61098.023438     337.5s     100 loci  split  (live; 8 queued)
      12. 61098.019531-61098.021484     168.8s       0 loci  accepted  (live; 7 queued)
      13. 61098.021484-61098.023438     168.8s     100 loci  split  (live; 8 queued)
      14. 61098.021484-61098.022461      84.4s      86 loci  accepted  (live; 7 queued)
      15. 61098.022461-61098.023438      84.4s     100 loci  split  (live; 8 queued)
      16. 61098.022461-61098.022949      42.2s      66 loci  accepted  (live; 7 queued)
      17. 61098.022949-61098.023438      42.2s     100 loci  split  (live; 8 queued)
      18. 61098.022949-61098.023193      21.1s       0 loci  accepted  (live; 7 queued)
      19. 61098.023193-61098.023438      21.1s     100 loci  accepted_at_minimum_saturated  (live; 6 queued)
      20. 61098.023438-61098.031250     675.0s     100 loci  split  (live; 7 queued)
      21. 61098.023438-61098.027344     337.5s     100 loci  split  (live; 8 queued)
      22. 61098.023438-61098.025391     168.8s     100 loci  split  (live; 9 queued)
      23. 61098.023438-61098.024414      84.4s     100 loci  split  (live; 10 queued)
      24. 61098.023438-61098.023926      42.2s      73 loci  accepted  (live; 9 queued)
      25. 61098.023926-61098.024414      42.2s      54 loci  accepted  (live; 8 queued)
      26. 61098.024414-61098.025391      84.4s     100 loci  split  (live; 9 queued)
      27. 61098.024414-61098.024902      42.2s     100 loci  split  (live; 10 queued)
      28. 61098.024414-61098.024658      21.1s     100 loci  accepted_at_minimum_saturated  (live; 9 queued)
      29. 61098.024658-61098.024902      21.1s       0 loci  accepted  (live; 8 queued)
      30. 61098.024902-61098.025391      42.2s      36 loci  accepted  (live; 7 queued)
      31. 61098.025391-61098.027344     168.8s     100 loci  split  (live; 8 queued)
      32. 61098.025391-61098.026367      84.4s     100 loci  split  (live; 9 queued)
      33. 61098.025391-61098.025879      42.2s     100 loci  split  (live; 10 queued)
      34. 61098.025391-61098.025635      21.1s      68 loci  accepted  (live; 9 queued)
      35. 61098.025635-61098.025879      21.1s      80 loci  accepted  (live; 8 queued)
      36. 61098.025879-61098.026367      42.2s     100 loci  split  (live; 9 queued)
      37. 61098.025879-61098.026123      21.1s       0 loci  accepted  (live; 8 queued)
      38. 61098.026123-61098.026367      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      39. 61098.026367-61098.027344      84.4s     100 loci  split  (live; 8 queued)
      40. 61098.026367-61098.026855      42.2s     100 loci  split  (live; 9 queued)
      41. 61098.026367-61098.026611      21.1s       0 loci  accepted  (live; 8 queued)
      42. 61098.026611-61098.026855      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      43. 61098.026855-61098.027344      42.2s     100 loci  split  (live; 8 queued)
      44. 61098.026855-61098.027100      21.1s       0 loci  accepted  (live; 7 queued)
      45. 61098.027100-61098.027344      21.1s     100 loci  accepted_at_minimum_saturated  (live; 6 queued)
      46. 61098.027344-61098.031250     337.5s     100 loci  split  (live; 7 queued)
      47. 61098.027344-61098.029297     168.8s     100 loci  split  (live; 8 queued)
      48. 61098.027344-61098.028320      84.4s     100 loci  split  (live; 9 queued)
      49. 61098.027344-61098.027832      42.2s     100 loci  split  (live; 10 queued)
      50. 61098.027344-61098.027588      21.1s       0 loci  accepted  (live; 9 queued)
      51. 61098.027588-61098.027832      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
    target reached (1,061/1,000); stopping with 8 unqueried chunks.
  History 2026/2/27: 1,000 unique loci from 22 accepted chunks  (29 splits, 122.4s)
  [WARN] 6 minimum-size chunks still reached the result cap. Use smaller chunks or add another partition such as RA slices.
  Lightcurve fetch disabled for this run.

SUCCESS 2026/2/27: saturated_unresolved  actual_loci=1000

========================================================================
Backfilling 2026/2/28  MJD [61099.0, 61100.0]

Attempt 1/5 for 2026/2/28
  Chunked query 'History 2026/2/28'  MJD [61099.000000, 61100.000000]
    ES limit=100, split at >= 95, minimum chunk=30s
       1. 61099.000000-61100.000000   86400.0s     100 loci  split  (live; 2 queued)
       2. 61099.000000-61099.500000   43200.0s     100 loci  split  (live; 3 queued)
       3. 61099.000000-61099.250000   21600.0s     100 loci  split  (live; 4 queued)
       4. 61099.000000-61099.125000   10800.0s     100 loci  split  (live; 5 queued)
       5. 61099.000000-61099.062500    5400.0s     100 loci  split  (live; 6 queued)
       6. 61099.000000-61099.031250    2700.0s       0 loci  accepted  (live; 5 queued)
       7. 61099.031250-61099.062500    2700.0s     100 loci  split  (live; 6 queued)
       8. 61099.031250-61099.046875    1350.0s     100 loci  split  (live; 7 queued)
       9. 61099.031250-61099.039062     675.0s       0 loci  accepted  (live; 6 queued)
      10. 61099.039062-61099.046875     675.0s     100 loci  split  (live; 7 queued)
      11. 61099.039062-61099.042969     337.5s     100 loci  split  (live; 8 queued)
      12. 61099.039062-61099.041016     168.8s     100 loci  split  (live; 9 queued)
      13. 61099.039062-61099.040039      84.4s     100 loci  split  (live; 10 queued)
      14. 61099.039062-61099.039551      42.2s       0 loci  accepted  (live; 9 queued)
      15. 61099.039551-61099.040039      42.2s     100 loci  split  (live; 10 queued)
      16. 61099.039551-61099.039795      21.1s       0 loci  accepted  (live; 9 queued)
      17. 61099.039795-61099.040039      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      18. 61099.040039-61099.041016      84.4s     100 loci  split  (live; 9 queued)
      19. 61099.040039-61099.040527      42.2s     100 loci  split  (live; 10 queued)
      20. 61099.040039-61099.040283      21.1s       0 loci  accepted  (live; 9 queued)
      21. 61099.040283-61099.040527      21.1s     100 loci  accepted_at_minimum_saturated  (live; 8 queued)
      22. 61099.040527-61099.041016      42.2s       0 loci  accepted  (live; 7 queued)
      23. 61099.041016-61099.042969     168.8s     100 loci  split  (live; 8 queued)
      24. 61099.041016-61099.041992      84.4s       0 loci  accepted  (live; 7 queued)
      25. 61099.041992-61099.042969      84.4s     100 loci  split  (live; 8 queued)
      26. 61099.041992-61099.042480      42.2s     100 loci  split  (live; 9 queued)
      27. 61099.041992-61099.042236      21.1s       0 loci  accepted  (live; 8 queued)
      28. 61099.042236-61099.042480      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      29. 61099.042480-61099.042969      42.2s       0 loci  accepted  (live; 6 queued)
      30. 61099.042969-61099.046875     337.5s     100 loci  split  (live; 7 queued)
      31. 61099.042969-61099.044922     168.8s     100 loci  split  (live; 8 queued)
      32. 61099.042969-61099.043945      84.4s     100 loci  split  (live; 9 queued)
      33. 61099.042969-61099.043457      42.2s      89 loci  accepted  (live; 8 queued)
      34. 61099.043457-61099.043945      42.2s     100 loci  split  (live; 9 queued)
      35. 61099.043457-61099.043701      21.1s       0 loci  accepted  (live; 8 queued)
      36. 61099.043701-61099.043945      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)
      37. 61099.043945-61099.044922      84.4s     100 loci  split  (live; 8 queued)
      38. 61099.043945-61099.044434      42.2s     100 loci  split  (live; 9 queued)
      39. 61099.043945-61099.044189      21.1s       0 loci  accepted  (live; 8 queued)
      40. 61099.044189-61099.044434      21.1s     100 loci  accepted_at_minimum_saturated  (live; 7 queued)

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
0,2026-02-24,2026/2/24,61095.0,61096.00,None,1000,1000,0,27,33,...,0,0,True,True,37.20,2026-05-24T09:02:52+00:00,2026-05-24T09:03:29+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
1,2026-02-25,2026/2/25,61096.0,61096.25,None,1000,1000,0,6,8,...,0,0,True,True,41.50,2026-05-23T22:05:01+00:00,2026-05-23T22:05:42+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
2,2026-02-26,2026/2/26,61097.0,61098.00,None,1000,1000,0,20,25,...,0,0,True,True,37.47,2026-05-24T09:03:29+00:00,2026-05-24T09:04:06+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
3,2026-02-27,2026/2/27,61098.0,61099.00,None,1000,1000,0,22,29,...,0,0,True,True,122.44,2026-05-24T09:04:07+00:00,2026-05-24T09:06:09+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
4,2026-02-28,2026/2/28,61099.0,61100.00,None,1000,1000,0,33,39,...,284,3,True,True,49.32,2026-05-24T09:06:09+00:00,2026-05-24T09:06:58+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...

[]

In [22]:
from pathlib import Path
import json
import time
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from antares_client.search import search as antares_search, get_by_id

from src import history, query


def _now_utc():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _sleep_for(attempt):
    return [20, 60, 120, 240, 480][min(attempt - 1, 4)]


def _query_loci_once(mjd_min, mjd_max, include_upper, ra_min, ra_max, limit, lsst_only=True):
    upper_op = "lte" if include_upper else "lt"

    filters = [
        {
            "range": {
                "properties.newest_alert_observation_time": {
                    "gte": float(mjd_min),
                    upper_op: float(mjd_max),
                }
            }
        },
        {"range": {"ra": {"gte": float(ra_min), "lt": float(ra_max)}}},
    ]

    if lsst_only:
        filters.append(query.lsst_identifier_filter())

    q = {"query": {"bool": {"filter": filters}}}

    rows = []
    for locus in antares_search(q):
        rows.append(query.locus_to_record(locus))
        if len(rows) >= limit:
            break

    return pd.DataFrame(rows)


def _query_loci_retry(*args, max_retries=6, **kwargs):
    last_error = None
    for attempt in range(1, max_retries + 1):
        try:
            return _query_loci_once(*args, **kwargs)
        except Exception as exc:
            last_error = exc
            print(f"      query failed attempt {attempt}/{max_retries}: {exc}")
            if attempt < max_retries:
                wait = _sleep_for(attempt)
                print(f"      sleeping {wait}s")
                time.sleep(wait)
    raise last_error


def full_loci_for_night(
    data_root,
    date_utc,
    mjd_min,
    mjd_max,
    lsst_only=True,
    max_results_per_chunk=100,
    split_threshold=95,
    min_chunk_seconds=30.0,
    min_ra_degrees=0.05,
    max_retries=6,
):
    cache_dir = Path(data_root) / "cache" / "full_loci_chunks" / date_utc
    cache_dir.mkdir(parents=True, exist_ok=True)

    pending = [(float(mjd_min), float(mjd_max), True, 0.0, 360.0)]
    accepted = []
    report = []
    saturated_leaf_count = 0
    attempt = 0

    while pending:
        lo, hi, include_upper, ra0, ra1 = pending.pop(0)
        attempt += 1
        width_seconds = (hi - lo) * 86400.0
        ra_width = ra1 - ra0

        cache_name = (
            f"mjd_{lo:.8f}_{hi:.8f}_"
            f"upper_{int(include_upper)}_ra_{ra0:.4f}_{ra1:.4f}.parquet"
        ).replace(".", "p")
        cache_path = cache_dir / cache_name

        if cache_path.exists():
            df = pd.read_parquet(cache_path)
            source = "cache"
        else:
            df = _query_loci_retry(
                lo,
                hi,
                include_upper,
                ra0,
                ra1,
                max_results_per_chunk,
                lsst_only=lsst_only,
                max_retries=max_retries,
            )
            source = "live"

        n = len(df)
        saturated = n >= split_threshold

        if saturated and width_seconds > min_chunk_seconds * 1.01:
            mid = (lo + hi) / 2.0
            pending.insert(0, (mid, hi, include_upper, ra0, ra1))
            pending.insert(0, (lo, mid, False, ra0, ra1))
            status = "split_time"

        elif saturated and ra_width > min_ra_degrees * 1.01:
            mid_ra = (ra0 + ra1) / 2.0
            pending.insert(0, (lo, hi, include_upper, mid_ra, ra1))
            pending.insert(0, (lo, hi, include_upper, ra0, mid_ra))
            status = "split_ra"

        else:
            if source == "live":
                df.to_parquet(cache_path, index=False)
            accepted.append(df)
            status = "accepted_saturated" if saturated else "accepted"
            if saturated:
                saturated_leaf_count += 1

        report.append({
            "mjd_min": lo,
            "mjd_max": hi,
            "include_upper": include_upper,
            "ra_min": ra0,
            "ra_max": ra1,
            "width_seconds": width_seconds,
            "n_loci": n,
            "status": status,
            "source": source,
        })

        print(
            f"    {attempt:>5}. MJD {lo:.6f}-{hi:.6f} "
            f"RA {ra0:7.2f}-{ra1:7.2f} "
            f"{n:>5} loci {status} ({source}; {len(pending)} queued)"
        )

    if accepted:
        loci = pd.concat(accepted, ignore_index=True, sort=False)
        loci = loci.drop_duplicates("locus_id", keep="last").reset_index(drop=True)
    else:
        loci = pd.DataFrame()

    return loci, pd.DataFrame(report), saturated_leaf_count


def _fetch_one_lightcurve_cached(locus_id, label, cache_dir, max_retries=6):
    cache_path = Path(cache_dir) / f"{locus_id}.parquet"
    if cache_path.exists():
        return pd.read_parquet(cache_path), None

    last_error = None
    for attempt in range(1, max_retries + 1):
        try:
            locus = get_by_id(locus_id)
            lc = locus.lightcurve
            if lc is None or lc.empty:
                empty = pd.DataFrame({"locus_id": [locus_id], "range_label": [label], "empty_lightcurve": [True]})
                empty.to_parquet(cache_path, index=False)
                return empty, None

            lc = lc.copy()
            lc["locus_id"] = locus_id
            lc["range_label"] = label
            lc.to_parquet(cache_path, index=False)
            return lc, None

        except Exception as exc:
            last_error = str(exc)
            if attempt < max_retries:
                time.sleep(_sleep_for(attempt))

    return None, last_error


def fetch_lightcurves_resumable(df_loci, label, cache_dir, max_workers=4, max_retries=6):
    cache_dir = Path(cache_dir)
    cache_dir.mkdir(parents=True, exist_ok=True)

    locus_ids = df_loci["locus_id"].dropna().astype(str).drop_duplicates().tolist()
    frames = []
    failures = []

    print(f"  Fetching {len(locus_ids):,} lightcurves with {max_workers} workers")

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {
            pool.submit(_fetch_one_lightcurve_cached, lid, label, cache_dir, max_retries): lid
            for lid in locus_ids
        }

        for i, future in enumerate(as_completed(futures), start=1):
            lid = futures[future]
            frame, err = future.result()
            if err:
                failures.append({"locus_id": lid, "error": err})
            elif frame is not None:
                frames.append(frame)

            if i % 100 == 0 or i == len(locus_ids):
                print(f"    {i}/{len(locus_ids)} lightcurves done; failures={len(failures)}")

    alerts = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    return alerts, pd.DataFrame(failures)


def ingest_full_night_no_compromise(
    data_root,
    mjd_min,
    mjd_max,
    lsst_only=True,
    overwrite_mismatched=True,
    max_results_per_chunk=100,
    split_threshold=95,
    min_chunk_seconds=30.0,
    min_ra_degrees=0.05,
    max_retries=6,
    lightcurve_workers=4,
):
    data_root = Path(data_root)
    date_utc = history.mjd_to_utc_date(mjd_min)
    label = f"Full History {history.display_date(date_utc)}"
    paths = history.nightly_paths(data_root, date_utc)

    existing = history.read_manifest(data_root, date_utc)
    if existing:
        same_window = (
            abs(float(existing.get("mjd_min", -1)) - float(mjd_min)) < 1e-9
            and abs(float(existing.get("mjd_max", -1)) - float(mjd_max)) < 1e-9
        )
        has_lightcurves = int(existing.get("alert_rows", 0)) > 0
        if same_window and has_lightcurves and existing.get("status") == "complete":
            print(f"  Resume: complete full night with lightcurves already exists for {date_utc}")
            return existing
        if overwrite_mismatched:
            print(f"  Existing partition for {date_utc} is incomplete/mismatched; overwriting it.")

    started = _now_utc()
    t0 = time.time()

    print(f"\nFULL NIGHT {date_utc}  MJD [{mjd_min}, {mjd_max}]")
    print("  Stage 1: exhaustive LSST-only locus extraction")

    df_raw, report, saturated_leaf_count = full_loci_for_night(
        data_root=data_root,
        date_utc=date_utc,
        mjd_min=mjd_min,
        mjd_max=mjd_max,
        lsst_only=lsst_only,
        max_results_per_chunk=max_results_per_chunk,
        split_threshold=split_threshold,
        min_chunk_seconds=min_chunk_seconds,
        min_ra_degrees=min_ra_degrees,
        max_retries=max_retries,
    )

    ingested_at = _now_utc()
    df_loci = history.prepare_loci(df_raw, date_utc, mjd_min, mjd_max, ingested_at)
    paths["dir"].mkdir(parents=True, exist_ok=True)
    df_loci.to_parquet(paths["loci"], index=False)
    report.to_parquet(paths["dir"] / "chunk_report.parquet", index=False)

    if saturated_leaf_count:
        raise RuntimeError(
            f"{date_utc} still has {saturated_leaf_count} saturated final chunks. "
            "Lower min_ra_degrees before accepting this as complete."
        )

    print("  Stage 2: full lightcurve extraction")
    df_alerts_raw, lc_failures = fetch_lightcurves_resumable(
        df_loci,
        label,
        Path(data_root) / "cache" / "lightcurves" / date_utc,
        max_workers=lightcurve_workers,
        max_retries=max_retries,
    )

    if not lc_failures.empty:
        lc_failures.to_parquet(paths["dir"] / "lightcurve_failures.parquet", index=False)
        raise RuntimeError(
            f"{date_utc} has {len(lc_failures)} lightcurve failures after retries. "
            "Rerun the same cell; cached successes will be reused."
        )

    df_alerts = history.prepare_alerts(df_alerts_raw, date_utc, label)
    df_alerts.to_parquet(paths["alerts"], index=False)

    validation = history.validation_summary(
        df_loci,
        df_alerts,
        mjd_min=mjd_min,
        mjd_max=mjd_max,
        lsst_only=lsst_only,
    )
    counts = query.lsst_identifier_counts(df_loci)

    manifest = {
        "date_utc": date_utc,
        "mjd_min": float(mjd_min),
        "mjd_max": float(mjd_max),
        "query_tag": None,
        "target_loci": None,
        "actual_loci": int(len(df_loci)),
        "alert_rows": int(len(df_alerts)),
        "chunk_count": int((report["status"].str.startswith("accepted")).sum()),
        "split_count": int((report["status"].str.startswith("split")).sum()),
        "saturated_chunk_count": int(saturated_leaf_count),
        "status": "complete",
        "survey_mode": "lsst",
        "lsst_filter_used": bool(lsst_only),
        "lsst_filter": query.lsst_identifier_filter() if lsst_only else None,
        "parallel_shards": 1,
        "lsst_dia_count": counts["lsst_dia_count"],
        "lsst_ss_count": counts["lsst_ss_count"],
        "ztf_object_id_count": counts["ztf_object_id_count"],
        "started_at_utc": started,
        "finished_at_utc": _now_utc(),
        "runtime_seconds": round(time.time() - t0, 2),
        "validation": validation,
        "paths": {
            "loci": str(paths["loci"]),
            "alerts": str(paths["alerts"]),
            "manifest": str(paths["manifest"]),
        },
    }

    with open(paths["manifest"], "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    history.update_cumulative_indexes(data_root)
    print(f"  COMPLETE {date_utc}: {len(df_loci):,} loci, {len(df_alerts):,} alert rows")
    return manifest

In [23]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")

manifests = []
failures = []

for date_utc, lo, hi in history.iter_night_windows(61095.0, 61100.0):
    try:
        manifest = ingest_full_night_no_compromise(
            data_root=DATA_ROOT,
            mjd_min=lo,
            mjd_max=hi,
            lsst_only=True,
            overwrite_mismatched=True,
            max_results_per_chunk=100,
            split_threshold=95,
            min_chunk_seconds=30.0,
            min_ra_degrees=0.05,
            max_retries=6,
            lightcurve_workers=4,
        )
        manifests.append(manifest)
    except Exception as exc:
        print(f"\nFAILED {date_utc}: {exc}")
        failures.append((date_utc, lo, hi, str(exc)))
        break

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("Finished nights:", len(manifests))
print("Failures:", failures)
print("Cumulative loci rows:", len(loci_index))
display(nightly_summary)

  Existing partition for 2026-02-24 is incomplete/mismatched; overwriting it.

FULL NIGHT 2026-02-24  MJD [61095.0, 61096.0]
  Stage 1: exhaustive LSST-only locus extraction
        1. MJD 61095.000000-61096.000000 RA    0.00- 360.00   100 loci split_time (live; 2 queued)
        2. MJD 61095.000000-61095.500000 RA    0.00- 360.00   100 loci split_time (live; 3 queued)
        3. MJD 61095.000000-61095.250000 RA    0.00- 360.00   100 loci split_time (live; 4 queued)
        4. MJD 61095.000000-61095.125000 RA    0.00- 360.00   100 loci split_time (live; 5 queued)
        5. MJD 61095.000000-61095.062500 RA    0.00- 360.00   100 loci split_time (live; 6 queued)
        6. MJD 61095.000000-61095.031250 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
        7. MJD 61095.000000-61095.015625 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
        8. MJD 61095.015625-61095.031250 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
        9. MJD 61095.015625-61095.023438 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       10. MJD 61095.015625-61095.019531 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
       11. MJD 61095.019531-61095.023438 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       12. MJD 61095.019531-61095.021484 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
       13. MJD 61095.021484-61095.023438 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       14. MJD 61095.021484-61095.022461 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
       15. MJD 61095.022461-61095.023438 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       16. MJD 61095.022461-61095.022949 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
       17. MJD 61095.022949-61095.023438 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       18. MJD 61095.022949-61095.023193 RA    0.00- 360.00   100 loci split_ra (live; 9 queued)
       19. MJD 61095.022949-61095.023193 RA    0.00- 180.00   100 loci split_ra (live; 10 queued)
       20. MJD 61095.022949-61095.023193 RA    0.00-  90.00   100 loci split_ra (live; 11 queued)
       21. MJD 61095.022949-61095.023193 RA    0.00-  45.00     0 loci accepted (live; 10 queued)
       22. MJD 61095.022949-61095.023193 RA   45.00-  90.00   100 loci split_ra (live; 11 queued)
       23. MJD 61095.022949-61095.023193 RA   45.00-  67.50   100 loci split_ra (live; 12 queued)
       24. MJD 61095.022949-61095.023193 RA   45.00-  56.25     0 loci accepted (live; 11 queued)
       25. MJD 61095.022949-61095.023193 RA   56.25-  67.50   100 loci split_ra (live; 12 queued)
       26. MJD 61095.022949-61095.023193 RA   56.25-  61.88   100 loci split_ra (live; 13 queued)
       27. MJD 61095.022949-61095.023193 RA   56.25-  59.06   100 loci split_ra (live; 14 queued)
       28. MJD 61095.022949-61095.023193 RA   56.25-  57.66    42 loci accepted (live; 13 queued)
       29. MJD 61095.022949-61095.023193 RA   57.66-  59.06   100 loci split_ra (live; 14 queued)
       30. MJD 61095.022949-61095.023193 RA   57.66-  58.36    67 loci accepted (live; 13 queued)
       31. MJD 61095.022949-61095.023193 RA   58.36-  59.06    71 loci accepted (live; 12 queued)
       32. MJD 61095.022949-61095.023193 RA   59.06-  61.88   100 loci split_ra (live; 13 queued)
       33. MJD 61095.022949-61095.023193 RA   59.06-  60.47   100 loci split_ra (live; 14 queued)
       34. MJD 61095.022949-61095.023193 RA   59.06-  59.77    58 loci accepted (live; 13 queued)
       35. MJD 61095.022949-61095.023193 RA   59.77-  60.47    92 loci accepted (live; 12 queued)
       36. MJD 61095.022949-61095.023193 RA   60.47-  61.88   100 loci split_ra (live; 13 queued)
       37. MJD 61095.022949-61095.023193 RA   60.47-  61.17    64 loci accepted (live; 12 queued)
       38. MJD 61095.022949-61095.023193 RA   61.17-  61.88    45 loci accepted (live; 11 queued)
       39. MJD 61095.022949-61095.023193 RA   61.88-  67.50    43 loci accepted (live; 10 queued)
       40. MJD 61095.022949-61095.023193 RA   67.50-  90.00     0 loci accepted (live; 9 queued)
       41. MJD 61095.022949-61095.023193 RA   90.00- 180.00     0 loci accepted (live; 8 queued)
       42. MJD 61095.022949-61095.023193 RA  180.00- 360.00     0 loci accepted (live; 7 queued)
       43. MJD 61095.023193-61095.023438 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
       44. MJD 61095.023438-61095.031250 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
       45. MJD 61095.023438-61095.027344 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
       46. MJD 61095.023438-61095.025391 RA    0.00- 360.00   100 loci split_time (live; 9 queued)
       47. MJD 61095.023438-61095.024414 RA    0.00- 360.00   100 loci split_time (live; 10 queued)
       48. MJD 61095.023438-61095.023926 RA    0.00- 360.00   100 loci split_time (live; 11 queued)
       49. MJD 61095.023438-61095.023682 RA    0.00- 360.00   100 loci split_ra (live; 12 queued)
       50. MJD 61095.023438-61095.023682 RA    0.00- 180.00   100 loci split_ra (live; 13 queued)
       51. MJD 61095.023438-61095.023682 RA    0.00-  90.00   100 loci split_ra (live; 14 queued)
       52. MJD 61095.023438-61095.023682 RA    0.00-  45.00     0 loci accepted (live; 13 queued)
       53. MJD 61095.023438-61095.023682 RA   45.00-  90.00   100 loci split_ra (live; 14 queued)
       54. MJD 61095.023438-61095.023682 RA   45.00-  67.50   100 loci split_ra (live; 15 queued)
       55. MJD 61095.023438-61095.023682 RA   45.00-  56.25     0 loci accepted (live; 14 queued)
       56. MJD 61095.023438-61095.023682 RA   56.25-  67.50   100 loci split_ra (live; 15 queued)
       57. MJD 61095.023438-61095.023682 RA   56.25-  61.88   100 loci split_ra (live; 16 queued)
       58. MJD 61095.023438-61095.023682 RA   56.25-  59.06     0 loci accepted (live; 15 queued)
       59. MJD 61095.023438-61095.023682 RA   59.06-  61.88   100 loci split_ra (live; 16 queued)
       60. MJD 61095.023438-61095.023682 RA   59.06-  60.47    17 loci accepted (live; 15 queued)
       61. MJD 61095.023438-61095.023682 RA   60.47-  61.88   100 loci split_ra (live; 16 queued)
       62. MJD 61095.023438-61095.023682 RA   60.47-  61.17    48 loci accepted (live; 15 queued)
       63. MJD 61095.023438-61095.023682 RA   61.17-  61.88    54 loci accepted (live; 14 queued)
       64. MJD 61095.023438-61095.023682 RA   61.88-  67.50   100 loci split_ra (live; 15 queued)
       65. MJD 61095.023438-61095.023682 RA   61.88-  64.69   100 loci split_ra (live; 16 queued)
       66. MJD 61095.023438-61095.023682 RA   61.88-  63.28   100 loci split_ra (live; 17 queued)
       67. MJD 61095.023438-61095.023682 RA   61.88-  62.58    68 loci accepted (live; 16 queued)
       68. MJD 61095.023438-61095.023682 RA   62.58-  63.28    75 loci accepted (live; 15 queued)
       69. MJD 61095.023438-61095.023682 RA   63.28-  64.69   100 loci split_ra (live; 16 queued)
       70. MJD 61095.023438-61095.023682 RA   63.28-  63.98   100 loci split_ra (live; 17 queued)
       71. MJD 61095.023438-61095.023682 RA   63.28-  63.63    60 loci accepted (live; 16 queued)
       72. MJD 61095.023438-61095.023682 RA   63.63-  63.98    46 loci accepted (live; 15 queued)
       73. MJD 61095.023438-61095.023682 RA   63.98-  64.69    59 loci accepted (live; 14 queued)
       74. MJD 61095.023438-61095.023682 RA   64.69-  67.50    35 loci accepted (live; 13 queued)
       75. MJD 61095.023438-61095.023682 RA   67.50-  90.00     0 loci accepted (live; 12 queued)
       76. MJD 61095.023438-61095.023682 RA   90.00- 180.00     0 loci accepted (live; 11 queued)
       77. MJD 61095.023438-61095.023682 RA  180.00- 360.00     0 loci accepted (live; 10 queued)
       78. MJD 61095.023682-61095.023926 RA    0.00- 360.00   100 loci split_ra (live; 11 queued)
       79. MJD 61095.023682-61095.023926 RA    0.00- 180.00   100 loci split_ra (live; 12 queued)
       80. MJD 61095.023682-61095.023926 RA    0.00-  90.00   100 loci split_ra (live; 13 queued)
       81. MJD 61095.023682-61095.023926 RA    0.00-  45.00     0 loci accepted (live; 12 queued)
       82. MJD 61095.023682-61095.023926 RA   45.00-  90.00   100 loci split_ra (live; 13 queued)
       83. MJD 61095.023682-61095.023926 RA   45.00-  67.50   100 loci split_ra (live; 14 queued)
       84. MJD 61095.023682-61095.023926 RA   45.00-  56.25     0 loci accepted (live; 13 queued)
       85. MJD 61095.023682-61095.023926 RA   56.25-  67.50   100 loci split_ra (live; 14 queued)
       86. MJD 61095.023682-61095.023926 RA   56.25-  61.88   100 loci split_ra (live; 15 queued)
       87. MJD 61095.023682-61095.023926 RA   56.25-  59.06   100 loci split_ra (live; 16 queued)
       88. MJD 61095.023682-61095.023926 RA   56.25-  57.66    98 loci split_ra (live; 17 queued)
       89. MJD 61095.023682-61095.023926 RA   56.25-  56.95    47 loci accepted (live; 16 queued)
       90. MJD 61095.023682-61095.023926 RA   56.95-  57.66    51 loci accepted (live; 15 queued)
       91. MJD 61095.023682-61095.023926 RA   57.66-  59.06   100 loci split_ra (live; 16 queued)
       92. MJD 61095.023682-61095.023926 RA   57.66-  58.36    95 loci split_ra (live; 17 queued)
       93. MJD 61095.023682-61095.023926 RA   57.66-  58.01    46 loci accepted (live; 16 queued)
       94. MJD 61095.023682-61095.023926 RA   58.01-  58.36    49 loci accepted (live; 15 queued)
       95. MJD 61095.023682-61095.023926 RA   58.36-  59.06    81 loci accepted (live; 14 queued)
       96. MJD 61095.023682-61095.023926 RA   59.06-  61.88   100 loci split_ra (live; 15 queued)
       97. MJD 61095.023682-61095.023926 RA   59.06-  60.47   100 loci split_ra (live; 16 queued)
       98. MJD 61095.023682-61095.023926 RA   59.06-  59.77   100 loci split_ra (live; 17 queued)
       99. MJD 61095.023682-61095.023926 RA   59.06-  59.41    46 loci accepted (live; 16 queued)
      100. MJD 61095.023682-61095.023926 RA   59.41-  59.77    60 loci accepted (live; 15 queued)
      101. MJD 61095.023682-61095.023926 RA   59.77-  60.47    91 loci accepted (live; 14 queued)
      102. MJD 61095.023682-61095.023926 RA   60.47-  61.88   100 loci split_ra (live; 15 queued)
      103. MJD 61095.023682-61095.023926 RA   60.47-  61.17    80 loci accepted (live; 14 queued)
      104. MJD 61095.023682-61095.023926 RA   61.17-  61.88    52 loci accepted (live; 13 queued)
      105. MJD 61095.023682-61095.023926 RA   61.88-  67.50     0 loci accepted (live; 12 queued)
      106. MJD 61095.023682-61095.023926 RA   67.50-  90.00     0 loci accepted (live; 11 queued)
      107. MJD 61095.023682-61095.023926 RA   90.00- 180.00     0 loci accepted (live; 10 queued)
      108. MJD 61095.023682-61095.023926 RA  180.00- 360.00     0 loci accepted (live; 9 queued)
      109. MJD 61095.023926-61095.024414 RA    0.00- 360.00   100 loci split_time (live; 10 queued)
      110. MJD 61095.023926-61095.024170 RA    0.00- 360.00     0 loci accepted (live; 9 queued)
      111. MJD 61095.024170-61095.024414 RA    0.00- 360.00   100 loci split_ra (live; 10 queued)
      112. MJD 61095.024170-61095.024414 RA    0.00- 180.00   100 loci split_ra (live; 11 queued)
      113. MJD 61095.024170-61095.024414 RA    0.00-  90.00   100 loci split_ra (live; 12 queued)
      114. MJD 61095.024170-61095.024414 RA    0.00-  45.00     0 loci accepted (live; 11 queued)
      115. MJD 61095.024170-61095.024414 RA   45.00-  90.00   100 loci split_ra (live; 12 queued)
      116. MJD 61095.024170-61095.024414 RA   45.00-  67.50   100 loci split_ra (live; 13 queued)
      117. MJD 61095.024170-61095.024414 RA   45.00-  56.25     0 loci accepted (live; 12 queued)
      118. MJD 61095.024170-61095.024414 RA   56.25-  67.50   100 loci split_ra (live; 13 queued)
      119. MJD 61095.024170-61095.024414 RA   56.25-  61.88   100 loci split_ra (live; 14 queued)
      120. MJD 61095.024170-61095.024414 RA   56.25-  59.06     0 loci accepted (live; 13 queued)
      121. MJD 61095.024170-61095.024414 RA   59.06-  61.88   100 loci split_ra (live; 14 queued)
      122. MJD 61095.024170-61095.024414 RA   59.06-  60.47    29 loci accepted (live; 13 queued)
      123. MJD 61095.024170-61095.024414 RA   60.47-  61.88   100 loci split_ra (live; 14 queued)
      124. MJD 61095.024170-61095.024414 RA   60.47-  61.17    46 loci accepted (live; 13 queued)
      125. MJD 61095.024170-61095.024414 RA   61.17-  61.88    60 loci accepted (live; 12 queued)
      126. MJD 61095.024170-61095.024414 RA   61.88-  67.50   100 loci split_ra (live; 13 queued)
      127. MJD 61095.024170-61095.024414 RA   61.88-  64.69   100 loci split_ra (live; 14 queued)
      128. MJD 61095.024170-61095.024414 RA   61.88-  63.28   100 loci split_ra (live; 15 queued)
      129. MJD 61095.024170-61095.024414 RA   61.88-  62.58    83 loci accepted (live; 14 queued)
      query failed attempt 1/6: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.024169921875%2C+%22lt%22%3A+61095.0244140625%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+62.578125%2C+%22lt%22%3A+63.28125%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=10&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf970f3a3c0>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
      130. MJD 61095.024170-61095.024414 RA   62.58-  63.28   100 loci split_ra (live; 15 queued)
      131. MJD 61095.024170-61095.024414 RA   62.58-  62.93    58 loci accepted (live; 14 queued)
      132. MJD 61095.024170-61095.024414 RA   62.93-  63.28    59 loci accepted (live; 13 queued)
      133. MJD 61095.024170-61095.024414 RA   63.28-  64.69   100 loci split_ra (live; 14 queued)
      134. MJD 61095.024170-61095.024414 RA   63.28-  63.98    67 loci accepted (live; 13 queued)
      135. MJD 61095.024170-61095.024414 RA   63.98-  64.69    66 loci accepted (live; 12 queued)
      136. MJD 61095.024170-61095.024414 RA   64.69-  67.50    39 loci accepted (live; 11 queued)
      137. MJD 61095.024170-61095.024414 RA   67.50-  90.00     0 loci accepted (live; 10 queued)
      138. MJD 61095.024170-61095.024414 RA   90.00- 180.00     0 loci accepted (live; 9 queued)
      139. MJD 61095.024170-61095.024414 RA  180.00- 360.00     0 loci accepted (live; 8 queued)
      140. MJD 61095.024414-61095.025391 RA    0.00- 360.00   100 loci split_time (live; 9 queued)
      141. MJD 61095.024414-61095.024902 RA    0.00- 360.00   100 loci split_time (live; 10 queued)
      142. MJD 61095.024414-61095.024658 RA    0.00- 360.00     0 loci accepted (live; 9 queued)
      143. MJD 61095.024658-61095.024902 RA    0.00- 360.00   100 loci split_ra (live; 10 queued)
      144. MJD 61095.024658-61095.024902 RA    0.00- 180.00   100 loci split_ra (live; 11 queued)
      145. MJD 61095.024658-61095.024902 RA    0.00-  90.00   100 loci split_ra (live; 12 queued)
      146. MJD 61095.024658-61095.024902 RA    0.00-  45.00     0 loci accepted (live; 11 queued)
      147. MJD 61095.024658-61095.024902 RA   45.00-  90.00   100 loci split_ra (live; 12 queued)
      148. MJD 61095.024658-61095.024902 RA   45.00-  67.50   100 loci split_ra (live; 13 queued)
      149. MJD 61095.024658-61095.024902 RA   45.00-  56.25     0 loci accepted (live; 12 queued)
      150. MJD 61095.024658-61095.024902 RA   56.25-  67.50   100 loci split_ra (live; 13 queued)
      151. MJD 61095.024658-61095.024902 RA   56.25-  61.88   100 loci split_ra (live; 14 queued)
      152. MJD 61095.024658-61095.024902 RA   56.25-  59.06   100 loci split_ra (live; 15 queued)
      153. MJD 61095.024658-61095.024902 RA   56.25-  57.66    57 loci accepted (live; 14 queued)
      154. MJD 61095.024658-61095.024902 RA   57.66-  59.06   100 loci split_ra (live; 15 queued)
      155. MJD 61095.024658-61095.024902 RA   57.66-  58.36    62 loci accepted (live; 14 queued)
      156. MJD 61095.024658-61095.024902 RA   58.36-  59.06    65 loci accepted (live; 13 queued)
      157. MJD 61095.024658-61095.024902 RA   59.06-  61.88   100 loci split_ra (live; 14 queued)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.024658203125%2C+%22lt%22%3A+61095.02490234375%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+59.0625%2C+%22lt%22%3A+60.46875%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=50&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf970758e30>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
      158. MJD 61095.024658-61095.024902 RA   59.06-  60.47   100 loci split_ra (live; 15 queued)
      159. MJD 61095.024658-61095.024902 RA   59.06-  59.77    95 loci split_ra (live; 16 queued)
      160. MJD 61095.024658-61095.024902 RA   59.06-  59.41    43 loci accepted (live; 15 queued)
      161. MJD 61095.024658-61095.024902 RA   59.41-  59.77    52 loci accepted (live; 14 queued)
      162. MJD 61095.024658-61095.024902 RA   59.77-  60.47    88 loci accepted (live; 13 queued)
      163. MJD 61095.024658-61095.024902 RA   60.47-  61.88   100 loci split_ra (live; 14 queued)
      164. MJD 61095.024658-61095.024902 RA   60.47-  61.17    63 loci accepted (live; 13 queued)
      165. MJD 61095.024658-61095.024902 RA   61.17-  61.88    40 loci accepted (live; 12 queued)
      166. MJD 61095.024658-61095.024902 RA   61.88-  67.50    16 loci accepted (live; 11 queued)
      167. MJD 61095.024658-61095.024902 RA   67.50-  90.00     0 loci accepted (live; 10 queued)
      168. MJD 61095.024658-61095.024902 RA   90.00- 180.00     0 loci accepted (live; 9 queued)
      169. MJD 61095.024658-61095.024902 RA  180.00- 360.00     0 loci accepted (live; 8 queued)
      170. MJD 61095.024902-61095.025391 RA    0.00- 360.00   100 loci split_time (live; 9 queued)
      171. MJD 61095.024902-61095.025146 RA    0.00- 360.00     0 loci accepted (live; 8 queued)
      172. MJD 61095.025146-61095.025391 RA    0.00- 360.00   100 loci split_ra (live; 9 queued)
      173. MJD 61095.025146-61095.025391 RA    0.00- 180.00   100 loci split_ra (live; 10 queued)
      174. MJD 61095.025146-61095.025391 RA    0.00-  90.00   100 loci split_ra (live; 11 queued)
      175. MJD 61095.025146-61095.025391 RA    0.00-  45.00     0 loci accepted (live; 10 queued)
      176. MJD 61095.025146-61095.025391 RA   45.00-  90.00   100 loci split_ra (live; 11 queued)
      177. MJD 61095.025146-61095.025391 RA   45.00-  67.50   100 loci split_ra (live; 12 queued)
      178. MJD 61095.025146-61095.025391 RA   45.00-  56.25     0 loci accepted (live; 11 queued)
      179. MJD 61095.025146-61095.025391 RA   56.25-  67.50   100 loci split_ra (live; 12 queued)
      180. MJD 61095.025146-61095.025391 RA   56.25-  61.88   100 loci split_ra (live; 13 queued)
      181. MJD 61095.025146-61095.025391 RA   56.25-  59.06     0 loci accepted (live; 12 queued)

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

    16161. MJD 61095.220703-61095.220947 RA  149.06- 150.47    88 loci accepted (live; 12 queued)
    16162. MJD 61095.220703-61095.220947 RA  150.47- 151.88    64 loci accepted (live; 11 queued)
    16163. MJD 61095.220703-61095.220947 RA  151.88- 157.50     0 loci accepted (live; 10 queued)
    16164. MJD 61095.220703-61095.220947 RA  157.50- 180.00     0 loci accepted (live; 9 queued)
    16165. MJD 61095.220703-61095.220947 RA  180.00- 360.00     0 loci accepted (live; 8 queued)
    16166. MJD 61095.220947-61095.221191 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
    16167. MJD 61095.221191-61095.221680 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
    16168. MJD 61095.221191-61095.221436 RA    0.00- 360.00   100 loci split_ra (live; 9 queued)
    16169. MJD 61095.221191-61095.221436 RA    0.00- 180.00   100 loci split_ra (live; 10 queued)
    16170. MJD 61095.221191-61095.221436 RA    0.00-  90.00     0 loci accepted (live; 9 queued)
    16171. MJD 61095.221191-61095.221436 RA   90.00- 180.00   100 loci split_ra (live; 10 queued)
    16172. MJD 61095.221191-61095.221436 RA   90.00- 135.00     0 loci accepted (live; 9 queued)
    16173. MJD 61095.221191-61095.221436 RA  135.00- 180.00   100 loci split_ra (live; 10 queued)
    16174. MJD 61095.221191-61095.221436 RA  135.00- 157.50   100 loci split_ra (live; 11 queued)
    16175. MJD 61095.221191-61095.221436 RA  135.00- 146.25     0 loci accepted (live; 10 queued)
    16176. MJD 61095.221191-61095.221436 RA  146.25- 157.50   100 loci split_ra (live; 11 queued)
    16177. MJD 61095.221191-61095.221436 RA  146.25- 151.88   100 loci split_ra (live; 12 queued)
    16178. MJD 61095.221191-61095.221436 RA  146.25- 149.06    55 loci accepted (live; 11 queued)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.22119140625%2C+%22lt%22%3A+61095.221435546875%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+149.0625%2C+%22lt%22%3A+151.875%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=50&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf9203cfe00>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
    16179. MJD 61095.221191-61095.221436 RA  149.06- 151.88   100 loci split_ra (live; 12 queued)
    16180. MJD 61095.221191-61095.221436 RA  149.06- 150.47   100 loci split_ra (live; 13 queued)
    16181. MJD 61095.221191-61095.221436 RA  149.06- 149.77   100 loci split_ra (live; 14 queued)
    16182. MJD 61095.221191-61095.221436 RA  149.06- 149.41    53 loci accepted (live; 13 queued)
    16183. MJD 61095.221191-61095.221436 RA  149.41- 149.77    74 loci accepted (live; 12 queued)
    16184. MJD 61095.221191-61095.221436 RA  149.77- 150.47   100 loci split_ra (live; 13 queued)
    16185. MJD 61095.221191-61095.221436 RA  149.77- 150.12    54 loci accepted (live; 12 queued)
    16186. MJD 61095.221191-61095.221436 RA  150.12- 150.47    66 loci accepted (live; 11 queued)
    16187. MJD 61095.221191-61095.221436 RA  150.47- 151.88   100 loci split_ra (live; 12 queued)
    16188. MJD 61095.221191-61095.221436 RA  150.47- 151.17    96 loci split_ra (live; 13 queued)
    16189. MJD 61095.221191-61095.221436 RA  150.47- 150.82    52 loci accepted (live; 12 queued)
    16190. MJD 61095.221191-61095.221436 RA  150.82- 151.17    44 loci accepted (live; 11 queued)
    16191. MJD 61095.221191-61095.221436 RA  151.17- 151.88    55 loci accepted (live; 10 queued)
    16192. MJD 61095.221191-61095.221436 RA  151.88- 157.50     0 loci accepted (live; 9 queued)
    16193. MJD 61095.221191-61095.221436 RA  157.50- 180.00     0 loci accepted (live; 8 queued)
    16194. MJD 61095.221191-61095.221436 RA  180.00- 360.00     0 loci accepted (live; 7 queued)
    16195. MJD 61095.221436-61095.221680 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16196. MJD 61095.221680-61095.222656 RA    0.00- 360.00     0 loci accepted (live; 5 queued)
    16197. MJD 61095.222656-61095.226562 RA    0.00- 360.00     0 loci accepted (live; 4 queued)
    16198. MJD 61095.226562-61095.234375 RA    0.00- 360.00     0 loci accepted (live; 3 queued)
    16199. MJD 61095.234375-61095.250000 RA    0.00- 360.00     0 loci accepted (live; 2 queued)
    16200. MJD 61095.250000-61095.500000 RA    0.00- 360.00   100 loci split_time (live; 3 queued)
    16201. MJD 61095.250000-61095.375000 RA    0.00- 360.00   100 loci split_time (live; 4 queued)
    16202. MJD 61095.250000-61095.312500 RA    0.00- 360.00   100 loci split_time (live; 5 queued)
    16203. MJD 61095.250000-61095.281250 RA    0.00- 360.00     0 loci accepted (live; 4 queued)
    16204. MJD 61095.281250-61095.312500 RA    0.00- 360.00   100 loci split_time (live; 5 queued)
    16205. MJD 61095.281250-61095.296875 RA    0.00- 360.00   100 loci split_time (live; 6 queued)
    16206. MJD 61095.281250-61095.289062 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16207. MJD 61095.281250-61095.285156 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16208. MJD 61095.285156-61095.289062 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16209. MJD 61095.285156-61095.287109 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16210. MJD 61095.287109-61095.289062 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16211. MJD 61095.287109-61095.288086 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16212. MJD 61095.288086-61095.289062 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16213. MJD 61095.288086-61095.288574 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
    16214. MJD 61095.288086-61095.288330 RA    0.00- 360.00   100 loci split_ra (live; 9 queued)
    16215. MJD 61095.288086-61095.288330 RA    0.00- 180.00     0 loci accepted (live; 8 queued)
    16216. MJD 61095.288086-61095.288330 RA  180.00- 360.00   100 loci split_ra (live; 9 queued)
    16217. MJD 61095.288086-61095.288330 RA  180.00- 270.00   100 loci split_ra (live; 10 queued)
    16218. MJD 61095.288086-61095.288330 RA  180.00- 225.00   100 loci split_ra (live; 11 queued)
    16219. MJD 61095.288086-61095.288330 RA  180.00- 202.50   100 loci split_ra (live; 12 queued)
    16220. MJD 61095.288086-61095.288330 RA  180.00- 191.25   100 loci split_ra (live; 13 queued)
    16221. MJD 61095.288086-61095.288330 RA  180.00- 185.62     0 loci accepted (live; 12 queued)
    16222. MJD 61095.288086-61095.288330 RA  185.62- 191.25   100 loci split_ra (live; 13 queued)
    16223. MJD 61095.288086-61095.288330 RA  185.62- 188.44   100 loci split_ra (live; 14 queued)
    16224. MJD 61095.288086-61095.288330 RA  185.62- 187.03   100 loci split_ra (live; 15 queued)
    16225. MJD 61095.288086-61095.288330 RA  185.62- 186.33   100 loci split_ra (live; 16 queued)
    16226. MJD 61095.288086-61095.288330 RA  185.62- 185.98    28 loci accepted (live; 15 queued)
    16227. MJD 61095.288086-61095.288330 RA  185.98- 186.33   100 loci split_ra (live; 16 queued)
    16228. MJD 61095.288086-61095.288330 RA  185.98- 186.15    43 loci accepted (live; 15 queued)
    16229. MJD 61095.288086-61095.288330 RA  186.15- 186.33    69 loci accepted (live; 14 queued)
    16230. MJD 61095.288086-61095.288330 RA  186.33- 187.03   100 loci split_ra (live; 15 queued)
    16231. MJD 61095.288086-61095.288330 RA  186.33- 186.68    80 loci accepted (live; 14 queued)
    16232. MJD 61095.288086-61095.288330 RA  186.68- 187.03   100 loci split_ra (live; 15 queued)
    16233. MJD 61095.288086-61095.288330 RA  186.68- 186.86    62 loci accepted (live; 14 queued)
    16234. MJD 61095.288086-61095.288330 RA  186.86- 187.03    49 loci accepted (live; 13 queued)
    16235. MJD 61095.288086-61095.288330 RA  187.03- 188.44    93 loci accepted (live; 12 queued)
    16236. MJD 61095.288086-61095.288330 RA  188.44- 191.25     0 loci accepted (live; 11 queued)
    16237. MJD 61095.288086-61095.288330 RA  191.25- 202.50     0 loci accepted (live; 10 queued)
    16238. MJD 61095.288086-61095.288330 RA  202.50- 225.00     0 loci accepted (live; 9 queued)
    16239. MJD 61095.288086-61095.288330 RA  225.00- 270.00     0 loci accepted (live; 8 queued)
    16240. MJD 61095.288086-61095.288330 RA  270.00- 360.00     0 loci accepted (live; 7 queued)
    16241. MJD 61095.288330-61095.288574 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16242. MJD 61095.288574-61095.289062 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16243. MJD 61095.288574-61095.288818 RA    0.00- 360.00     0 loci accepted (live; 6 queued)
    16244. MJD 61095.288818-61095.289062 RA    0.00- 360.00   100 loci split_ra (live; 7 queued)
    16245. MJD 61095.288818-61095.289062 RA    0.00- 180.00     0 loci accepted (live; 6 queued)
    16246. MJD 61095.288818-61095.289062 RA  180.00- 360.00   100 loci split_ra (live; 7 queued)
    16247. MJD 61095.288818-61095.289062 RA  180.00- 270.00   100 loci split_ra (live; 8 queued)
    16248. MJD 61095.288818-61095.289062 RA  180.00- 225.00   100 loci split_ra (live; 9 queued)
    16249. MJD 61095.288818-61095.289062 RA  180.00- 202.50   100 loci split_ra (live; 10 queued)
    16250. MJD 61095.288818-61095.289062 RA  180.00- 191.25   100 loci split_ra (live; 11 queued)
    16251. MJD 61095.288818-61095.289062 RA  180.00- 185.62   100 loci split_ra (live; 12 queued)
    16252. MJD 61095.288818-61095.289062 RA  180.00- 182.81     0 loci accepted (live; 11 queued)
    16253. MJD 61095.288818-61095.289062 RA  182.81- 185.62   100 loci split_ra (live; 12 queued)
    16254. MJD 61095.288818-61095.289062 RA  182.81- 184.22     0 loci accepted (live; 11 queued)
    16255. MJD 61095.288818-61095.289062 RA  184.22- 185.62   100 loci split_ra (live; 12 queued)
    16256. MJD 61095.288818-61095.289062 RA  184.22- 184.92    31 loci accepted (live; 11 queued)
    16257. MJD 61095.288818-61095.289062 RA  184.92- 185.62   100 loci split_ra (live; 12 queued)
    16258. MJD 61095.288818-61095.289062 RA  184.92- 185.27   100 loci split_ra (live; 13 queued)
    16259. MJD 61095.288818-61095.289062 RA  184.92- 185.10   100 loci split_ra (live; 14 queued)
    16260. MJD 61095.288818-61095.289062 RA  184.92- 185.01    32 loci accepted (live; 13 queued)
    16261. MJD 61095.288818-61095.289062 RA  185.01- 185.10    96 loci split_ra (live; 14 queued)
    16262. MJD 61095.288818-61095.289062 RA  185.01- 185.05    44 loci accepted (live; 13 queued)
    16263. MJD 61095.288818-61095.289062 RA  185.05- 185.10    52 loci accepted (live; 12 queued)
    16264. MJD 61095.288818-61095.289062 RA  185.10- 185.27   100 loci split_ra (live; 13 queued)
    16265. MJD 61095.288818-61095.289062 RA  185.10- 185.19    91 loci accepted (live; 12 queued)
    16266. MJD 61095.288818-61095.289062 RA  185.19- 185.27   100 loci split_ra (live; 13 queued)
    16267. MJD 61095.288818-61095.289062 RA  185.19- 185.23    58 loci accepted (live; 12 queued)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61095.288818359375%2C+%22lt%22%3A+61095.2890625%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+185.2294921875%2C+%22lt%22%3A+185.2734375%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=30&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf920063fb0>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
    16268. MJD 61095.288818-61095.289062 RA  185.23- 185.27    52 loci accepted (live; 11 queued)
    16269. MJD 61095.288818-61095.289062 RA  185.27- 185.62   100 loci split_ra (live; 12 queued)
    16270. MJD 61095.288818-61095.289062 RA  185.27- 185.45   100 loci split_ra (live; 13 queued)
    16271. MJD 61095.288818-61095.289062 RA  185.27- 185.36   100 loci split_ra (live; 14 queued)
    16272. MJD 61095.288818-61095.289062 RA  185.27- 185.32    59 loci accepted (live; 13 queued)
    16273. MJD 61095.288818-61095.289062 RA  185.32- 185.36    48 loci accepted (live; 12 queued)
    16274. MJD 61095.288818-61095.289062 RA  185.36- 185.45   100 loci split_ra (live; 13 queued)
    16275. MJD 61095.288818-61095.289062 RA  185.36- 185.41    54 loci accepted (live; 12 queued)
    16276. MJD 61095.288818-61095.289062 RA  185.41- 185.45    68 loci accepted (live; 11 queued)
    16277. MJD 61095.288818-61095.289062 RA  185.45- 185.62   100 loci split_ra (live; 12 queued)
    16278. MJD 61095.288818-61095.289062 RA  185.45- 185.54   100 loci split_ra (live; 13 queued)
    16279. MJD 61095.288818-61095.289062 RA  185.45- 185.49    86 loci accepted (live; 12 queued)
    16280. MJD 61095.288818-61095.289062 RA  185.49- 185.54    59 loci accepted (live; 11 queued)
    16281. MJD 61095.288818-61095.289062 RA  185.54- 185.62   100 loci split_ra (live; 12 queued)
    16282. MJD 61095.288818-61095.289062 RA  185.54- 185.58    50 loci accepted (live; 11 queued)
    16283. MJD 61095.288818-61095.289062 RA  185.58- 185.62    54 loci accepted (live; 10 queued)
    16284. MJD 61095.288818-61095.289062 RA  185.62- 191.25   100 loci split_ra (live; 11 queued)
    16285. MJD 61095.288818-61095.289062 RA  185.62- 188.44   100 loci split_ra (live; 12 queued)
    16286. MJD 61095.288818-61095.289062 RA  185.62- 187.03   100 loci split_ra (live; 13 queued)
    16287. MJD 61095.288818-61095.289062 RA  185.62- 186.33   100 loci split_ra (live; 14 queued)
    16288. MJD 61095.288818-61095.289062 RA  185.62- 185.98   100 loci split_ra (live; 15 queued)
    16289. MJD 61095.288818-61095.289062 RA  185.62- 185.80   100 loci split_ra (live; 16 queued)
    16290. MJD 61095.288818-61095.289062 RA  185.62- 185.71   100 loci split_ra (live; 17 queued)
    16291. MJD 61095.288818-61095.289062 RA  185.62- 185.67    51 loci accepted (live; 16 queued)
    16292. MJD 61095.288818-61095.289062 RA  185.67- 185.71    51 loci accepted (live; 15 queued)
    16293. MJD 61095.288818-61095.289062 RA  185.71- 185.80    99 loci split_ra (live; 16 queued)
    16294. MJD 61095.288818-61095.289062 RA  185.71- 185.76    43 loci accepted (live; 15 queued)
    16295. MJD 61095.288818-61095.289062 RA  185.76- 185.80    56 loci accepted (live; 14 queued)
    16296. MJD 61095.288818-61095.289062 RA  185.80- 185.98   100 loci split_ra (live; 15 queued)
    16297. MJD 61095.288818-61095.289062 RA  185.80- 185.89    86 loci accepted (live; 14 queued)
    16298. MJD 61095.288818-61095.289062 RA  185.89- 185.98    52 loci accepted (live; 13 queued)
    16299. MJD 61095.288818-61095.289062 RA  185.98- 186.33    24 loci accepted (live; 12 queued)
    16300. MJD 61095.288818-61095.289062 RA  186.33- 187.03     0 loci accepted (live; 11 queued)
    16301. MJD 61095.288818-61095.289062 RA  187.03- 188.44     0 loci accepted (live; 10 queued)
    16302. MJD 61095.288818-61095.289062 RA  188.44- 191.25     0 loci accepted (live; 9 queued)
    16303. MJD 61095.288818-61095.289062 RA  191.25- 202.50     0 loci accepted (live; 8 queued)
    16304. MJD 61095.288818-61095.289062 RA  202.50- 225.00     0 loci accepted (live; 7 queued)
    16305. MJD 61095.288818-61095.289062 RA  225.00- 270.00     0 loci accepted (live; 6 queued)
    16306. MJD 61095.288818-61095.289062 RA  270.00- 360.00     0 loci accepted (live; 5 queued)
    16307. MJD 61095.289062-61095.296875 RA    0.00- 360.00   100 loci split_time (live; 6 queued)
    16308. MJD 61095.289062-61095.292969 RA    0.00- 360.00   100 loci split_time (live; 7 queued)
    16309. MJD 61095.289062-61095.291016 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
    16310. MJD 61095.289062-61095.290039 RA    0.00- 360.00     0 loci accepted (live; 7 queued)
    16311. MJD 61095.290039-61095.291016 RA    0.00- 360.00   100 loci split_time (live; 8 queued)
    16312. MJD 61095.290039-61095.290527 RA    0.00- 360.00   100 loci split_time (live; 9 queued)
    16313. MJD 61095.290039-61095.290283 RA    0.00- 360.00     0 loci accepted (live; 8 queued)
    16314. MJD 61095.290283-61095.290527 RA    0.00- 360.00   100 loci split_ra (live; 9 queued)
    16315. MJD 61095.290283-61095.290527 RA    0.00- 180.00     0 loci accepted (live; 8 queued)
    16316. MJD 61095.290283-61095.290527 RA  180.00- 360.00   100 loci split_ra (live; 9 queued)
    16317. MJD 61095.290283-61095.290527 RA  180.00- 270.00   100 loci split_ra (live; 10 queued)
    16318. MJD 61095.290283-61095.290527 RA  180.00- 225.00   100 loci split_ra (live; 11 queued)
    16319. MJD 61095.290283-61095.290527 RA  180.00- 202.50   100 loci split_ra (live; 12 queued)
    16320. MJD 61095.290283-61095.290527 RA  180.00- 191.25   100 loci split_ra (live; 13 queued)
    16321. MJD 61095.290283-61095.290527 RA  180.00- 185.62    14 loci accepted (live; 12 queued)
    16322. MJD 61095.290283-61095.290527 RA  185.62- 191.25   100 loci split_ra (live; 13 queued)
    16323. MJD 61095.290283-61095.290527 RA  185.62- 188.44   100 loci split_ra (live; 14 queued)
    16324. MJD 61095.290283-61095.290527 RA  185.62- 187.03   100 loci split_ra (live; 15 queued)
    16325. MJD 61095.290283-61095.290527 RA  185.62- 186.33   100 loci split_ra (live; 16 queued)
    16326. MJD 61095.290283-61095.290527 RA  185.62- 185.98   100 loci split_ra (live; 17 queued)
    16327. MJD 61095.290283-61095.290527 RA  185.62- 185.80   100 loci split_ra (live; 18 queued)
    16328. MJD 61095.290283-61095.290527 RA  185.62- 185.71    45 loci accepted (live; 17 queued)
    16329. MJD 61095.290283-61095.290527 RA  185.71- 185.80    60 loci accepted (live; 16 queued)
    16330. MJD 61095.290283-61095.290527 RA  185.80- 185.98    88 loci accepted (live; 15 queued)
    16331. MJD 61095.290283-61095.290527 RA  185.98- 186.33   100 loci split_ra (live; 16 queued)
    16332. MJD 61095.290283-61095.290527 RA  185.98- 186.15    88 loci accepted (live; 15 queued)
    16333. MJD 61095.290283-61095.290527 RA  186.15- 186.33    99 loci split_ra (live; 16 queued)
    16334. MJD 61095.290283-61095.290527 RA  186.15- 186.24    50 loci accepted (live; 15 queued)
    16335. MJD 61095.290283-61095.290527 RA  186.24- 186.33    49 loci accepted (live; 14 queued)
    16336. MJD 61095.290283-61095.290527 RA  186.33- 187.03   100 loci split_ra (live; 15 queued)
    16337. MJD 61095.290283-61095.290527 RA  186.33- 186.68   100 loci split_ra (live; 16 queued)
    16338. MJD 61095.290283-61095.290527 RA  186.33- 186.50    70 loci accepted (live; 15 queued)
    16339. MJD 61095.290283-61095.290527 RA  186.50- 186.68    94 loci accepted (live; 14 queued)
    16340. MJD 61095.290283-61095.290527 RA  186.68- 187.03    65 loci accepted (live; 13 queued)
    16341. MJD 61095.290283-61095.290527 RA  187.03- 188.44     0 loci accepted (live; 12 queued)
    16342. MJD 61095.290283-61095.290527 RA  188.44- 191.25     0 loci accepted (live; 11 queued)
    16343. MJD 61095.290283-61095.290527 RA  191.25- 202.50     0 loci accepted (live; 10 queued)

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
0,2026-02-24,2026/2/24,61095.0,61096.00,None,1000,1000,0,27,33,...,0,0,True,True,37.20,2026-05-24T09:02:52+00:00,2026-05-24T09:03:29+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
1,2026-02-25,2026/2/25,61096.0,61096.25,None,1000,1000,0,6,8,...,0,0,True,True,41.50,2026-05-23T22:05:01+00:00,2026-05-23T22:05:42+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
2,2026-02-26,2026/2/26,61097.0,61098.00,None,1000,1000,0,20,25,...,0,0,True,True,37.47,2026-05-24T09:03:29+00:00,2026-05-24T09:04:06+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
3,2026-02-27,2026/2/27,61098.0,61099.00,None,1000,1000,0,22,29,...,0,0,True,True,122.44,2026-05-24T09:04:07+00:00,2026-05-24T09:06:09+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
4,2026-02-28,2026/2/28,61099.0,61100.00,None,1000,1000,0,33,39,...,284,3,True,True,49.32,2026-05-24T09:06:09+00:00,2026-05-24T09:06:58+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...

In [24]:
from pathlib import Path
import json
import time
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from antares_client.search import search as antares_search, get_by_id

from src import history, query


# ============================================================
# USER SETTINGS: CHANGE THESE FIRST
# ============================================================
DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")

# One full night. Change these two values for a different night.
MJD_START = 61096.0
MJD_STOP = 61097.0

FETCH_LIGHTCURVES = True

# Query geometry. Start here; tune only if needed.
TIME_BIN_MINUTES = 10
RA_BINS = 24
DEC_BINS = 6

# Moderate cap: faster than 100, safer than 10000.
MAX_RESULTS_PER_TILE = 500
SATURATION_THRESHOLD = 475

# Retry/cache behavior.
MAX_RETRIES = 6
LIGHTCURVE_WORKERS = 4

# Final safety floors. If a tile is still saturated below these,
# the night is not accepted as complete.
MIN_TIME_SECONDS = 30
MIN_RA_DEGREES = 0.05
MIN_DEC_DEGREES = 0.05


# ============================================================
# INTERNAL HELPERS
# ============================================================
def now_utc():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def retry_sleep(attempt):
    return [20, 60, 120, 240, 480][min(attempt - 1, 4)]


def frange(start, stop, step):
    x = float(start)
    while x < float(stop):
        y = min(x + step, float(stop))
        yield x, y
        x = y


def query_tile_once(mjd_min, mjd_max, ra_min, ra_max, dec_min, dec_max, include_upper):
    upper_op = "lte" if include_upper else "lt"

    q = {
        "query": {
            "bool": {
                "filter": [
                    {
                        "range": {
                            "properties.newest_alert_observation_time": {
                                "gte": float(mjd_min),
                                upper_op: float(mjd_max),
                            }
                        }
                    },
                    {"range": {"ra": {"gte": float(ra_min), "lt": float(ra_max)}}},
                    {"range": {"dec": {"gte": float(dec_min), "lt": float(dec_max)}}},
                    query.lsst_identifier_filter(),
                ]
            }
        }
    }

    rows = []
    for locus in antares_search(q):
        rows.append(query.locus_to_record(locus))
        if len(rows) >= MAX_RESULTS_PER_TILE:
            break

    return pd.DataFrame(rows)


def query_tile_with_retry(*args):
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            return query_tile_once(*args)
        except Exception as exc:
            last_error = exc
            print(f"      query failed attempt {attempt}/{MAX_RETRIES}: {exc}")
            if attempt < MAX_RETRIES:
                wait = retry_sleep(attempt)
                print(f"      sleeping {wait}s")
                time.sleep(wait)
    raise last_error


def tile_cache_path(cache_dir, tile):
    mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
    name = (
        f"mjd_{mjd0:.8f}_{mjd1:.8f}_"
        f"ra_{ra0:.4f}_{ra1:.4f}_"
        f"dec_{dec0:.4f}_{dec1:.4f}_"
        f"upper_{int(include_upper)}.parquet"
    ).replace(".", "p").replace("-", "m")
    return cache_dir / name


def split_tile(tile):
    mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
    time_seconds = (mjd1 - mjd0) * 86400.0
    ra_width = ra1 - ra0
    dec_width = dec1 - dec0

    # Prefer sky splitting before going too tiny in time.
    if dec_width > MIN_DEC_DEGREES * 1.01:
        mid = (dec0 + dec1) / 2.0
        return [
            (mjd0, mjd1, ra0, ra1, dec0, mid, include_upper),
            (mjd0, mjd1, ra0, ra1, mid, dec1, include_upper),
        ]

    if ra_width > MIN_RA_DEGREES * 1.01:
        mid = (ra0 + ra1) / 2.0
        return [
            (mjd0, mjd1, ra0, mid, dec0, dec1, include_upper),
            (mjd0, mjd1, mid, ra1, dec0, dec1, include_upper),
        ]

    if time_seconds > MIN_TIME_SECONDS * 1.01:
        mid = (mjd0 + mjd1) / 2.0
        return [
            (mjd0, mid, ra0, ra1, dec0, dec1, False),
            (mid, mjd1, ra0, ra1, dec0, dec1, include_upper),
        ]

    return []


def extract_full_loci_for_night(data_root, mjd_start, mjd_stop):
    date_utc = history.mjd_to_utc_date(mjd_start)
    cache_dir = data_root / "cache" / "tile_loci" / date_utc
    cache_dir.mkdir(parents=True, exist_ok=True)

    time_step = TIME_BIN_MINUTES / 1440.0
    ra_step = 360.0 / RA_BINS
    dec_step = 180.0 / DEC_BINS

    pending = []
    for mjd0, mjd1 in frange(mjd_start, mjd_stop, time_step):
        include_upper = mjd1 >= mjd_stop
        for ra0, ra1 in frange(0.0, 360.0, ra_step):
            for dec0, dec1 in frange(-90.0, 90.0, dec_step):
                pending.append((mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper))

    accepted_paths = []
    report_rows = []
    saturated_final = []
    n_done = 0

    print(f"Initial tiles: {len(pending):,}")

    while pending:
        tile = pending.pop(0)
        mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
        path = tile_cache_path(cache_dir, tile)

        if path.exists():
            df = pd.read_parquet(path)
            source = "cache"
        else:
            df = query_tile_with_retry(mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper)
            source = "live"

        n = len(df)
        saturated = n >= SATURATION_THRESHOLD

        if saturated:
            children = split_tile(tile)
            if children:
                pending = children + pending
                status = "split"
            else:
                df.to_parquet(path, index=False)
                accepted_paths.append(path)
                saturated_final.append(tile)
                status = "accepted_saturated_final"
        else:
            df.to_parquet(path, index=False)
            accepted_paths.append(path)
            status = "accepted"

        n_done += 1
        report_rows.append({
            "mjd_min": mjd0,
            "mjd_max": mjd1,
            "ra_min": ra0,
            "ra_max": ra1,
            "dec_min": dec0,
            "dec_max": dec1,
            "include_upper": include_upper,
            "n_loci": n,
            "status": status,
            "source": source,
            "remaining": len(pending),
        })

        if n_done % 100 == 0 or saturated or status.startswith("accepted_saturated"):
            print(
                f"{n_done:>6} done | {len(pending):>6} queued | "
                f"MJD {mjd0:.6f}-{mjd1:.6f} "
                f"RA {ra0:6.1f}-{ra1:6.1f} "
                f"Dec {dec0:6.1f}-{dec1:6.1f} "
                f"{n:>4} loci {status} ({source})"
            )

    frames = [pd.read_parquet(p) for p in accepted_paths]
    loci = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    if not loci.empty and "locus_id" in loci.columns:
        loci = loci.drop_duplicates("locus_id", keep="last").reset_index(drop=True)

    report = pd.DataFrame(report_rows)
    return loci, report, saturated_final


def fetch_one_lc_cached(locus_id, label, cache_dir):
    path = cache_dir / f"{locus_id}.parquet"
    if path.exists():
        return pd.read_parquet(path), None

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            locus = get_by_id(locus_id)
            lc = locus.lightcurve
            if lc is None or lc.empty:
                lc = pd.DataFrame({
                    "locus_id": [locus_id],
                    "range_label": [label],
                    "empty_lightcurve": [True],
                })
            else:
                lc = lc.copy()
                lc["locus_id"] = locus_id
                lc["range_label"] = label

            lc.to_parquet(path, index=False)
            return lc, None

        except Exception as exc:
            last_error = str(exc)
            if attempt < MAX_RETRIES:
                time.sleep(retry_sleep(attempt))

    return None, last_error


def fetch_all_lightcurves(df_loci, date_utc, label, data_root):
    cache_dir = data_root / "cache" / "lightcurves" / date_utc
    cache_dir.mkdir(parents=True, exist_ok=True)

    locus_ids = df_loci["locus_id"].dropna().astype(str).drop_duplicates().tolist()
    frames = []
    failures = []

    print(f"Fetching {len(locus_ids):,} lightcurves with {LIGHTCURVE_WORKERS} workers")

    with ThreadPoolExecutor(max_workers=LIGHTCURVE_WORKERS) as pool:
        futures = {
            pool.submit(fetch_one_lc_cached, lid, label, cache_dir): lid
            for lid in locus_ids
        }

        for i, future in enumerate(as_completed(futures), start=1):
            lid = futures[future]
            frame, err = future.result()
            if err:
                failures.append({"locus_id": lid, "error": err})
            elif frame is not None:
                frames.append(frame)

            if i % 100 == 0 or i == len(locus_ids):
                print(f"  {i}/{len(locus_ids)} lightcurves complete; failures={len(failures)}")

    alerts = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    return alerts, pd.DataFrame(failures)


# ============================================================
# RUN ONE FULL NIGHT
# ============================================================
DATA_ROOT.mkdir(parents=True, exist_ok=True)

date_utc = history.mjd_to_utc_date(MJD_START)
label = f"Full History {history.display_date(date_utc)}"
paths = history.nightly_paths(DATA_ROOT, date_utc)
paths["dir"].mkdir(parents=True, exist_ok=True)

print(f"FULL NIGHT: {date_utc}")
print(f"MJD range : [{MJD_START}, {MJD_STOP}]")
print(f"Data root : {DATA_ROOT}")

started = now_utc()
t0 = time.time()

print("\nStage 1: full LSST-only locus extraction")
df_loci_raw, tile_report, saturated_final = extract_full_loci_for_night(
    DATA_ROOT,
    MJD_START,
    MJD_STOP,
)

tile_report.to_parquet(paths["dir"] / "tile_report.parquet", index=False)

if saturated_final:
    print(f"\nNOT COMPLETE: {len(saturated_final)} final saturated tiles remain.")
    print("Lower MAX_RESULTS_PER_TILE risk is not the fix; lower MIN_RA_DEGREES/MIN_DEC_DEGREES or increase initial sky bins.")
    raise RuntimeError(f"{date_utc} has saturated final tiles; not accepting as complete.")

df_loci = history.prepare_loci(df_loci_raw, date_utc, MJD_START, MJD_STOP, now_utc())
df_loci.to_parquet(paths["loci"], index=False)

print(f"Loci complete: {len(df_loci):,}")

if FETCH_LIGHTCURVES:
    print("\nStage 2: full lightcurve extraction")
    df_alerts_raw, lc_failures = fetch_all_lightcurves(df_loci, date_utc, label, DATA_ROOT)

    if not lc_failures.empty:
        lc_failures.to_parquet(paths["dir"] / "lightcurve_failures.parquet", index=False)
        raise RuntimeError(f"{len(lc_failures)} lightcurves failed after retries. Rerun this cell to resume.")

    df_alerts = history.prepare_alerts(df_alerts_raw, date_utc, label)
else:
    df_alerts = history.prepare_alerts(pd.DataFrame(), date_utc, label)

df_alerts.to_parquet(paths["alerts"], index=False)

validation = history.validation_summary(
    df_loci,
    df_alerts,
    mjd_min=MJD_START,
    mjd_max=MJD_STOP,
    lsst_only=True,
)

counts = query.lsst_identifier_counts(df_loci)

manifest = {
    "date_utc": date_utc,
    "mjd_min": float(MJD_START),
    "mjd_max": float(MJD_STOP),
    "query_tag": None,
    "target_loci": None,
    "actual_loci": int(len(df_loci)),
    "alert_rows": int(len(df_alerts)),
    "chunk_count": int((tile_report["status"].str.startswith("accepted")).sum()),
    "split_count": int((tile_report["status"] == "split").sum()),
    "saturated_chunk_count": 0,
    "status": "complete",
    "survey_mode": "lsst",
    "lsst_filter_used": True,
    "lsst_filter": query.lsst_identifier_filter(),
    "parallel_shards": 1,
    "lsst_dia_count": counts["lsst_dia_count"],
    "lsst_ss_count": counts["lsst_ss_count"],
    "ztf_object_id_count": counts["ztf_object_id_count"],
    "started_at_utc": started,
    "finished_at_utc": now_utc(),
    "runtime_seconds": round(time.time() - t0, 2),
    "validation": validation,
    "paths": {
        "loci": str(paths["loci"]),
        "alerts": str(paths["alerts"]),
        "manifest": str(paths["manifest"]),
    },
}

with open(paths["manifest"], "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, sort_keys=True)
    f.write("\n")

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("\nCOMPLETE")
print("Date:", date_utc)
print("Loci:", len(df_loci))
print("Alert/lightcurve rows:", len(df_alerts))
print("Runtime seconds:", manifest["runtime_seconds"])
display(nightly_summary.tail())

FULL NIGHT: 2026-02-25
MJD range : [61096.0, 61097.0]
Data root : /home/mdarim/ANTARES_Analysis_Data

Stage 1: full LSST-only locus extraction
Initial tiles: 20,736
   100 done |  20636 queued | MJD 61096.000000-61096.006944 RA  240.0- 255.0 Dec    0.0-  30.0    0 loci accepted (live)
   200 done |  20536 queued | MJD 61096.006944-61096.013889 RA  135.0- 150.0 Dec  -60.0- -30.0    0 loci accepted (live)
   300 done |  20436 queued | MJD 61096.013889-61096.020833 RA   15.0-  30.0 Dec   60.0-  90.0    0 loci accepted (live)
   400 done |  20336 queued | MJD 61096.013889-61096.020833 RA  270.0- 285.0 Dec    0.0-  30.0    0 loci accepted (live)
   500 done |  20236 queued | MJD 61096.020833-61096.027778 RA  165.0- 180.0 Dec  -60.0- -30.0    0 loci accepted (live)
   596 done |  20142 queued | MJD 61096.027778-61096.034722 RA   45.0-  60.0 Dec  -60.0- -30.0  500 loci split (live)
   597 done |  20143 queued | MJD 61096.027778-61096.034722 RA   45.0-  60.0 Dec  -60.0- -45.0  500 loci split (live)
   599 done |  20143 queued | MJD 61096.027778-61096.034722 RA   45.0-  60.0 Dec  -52.5- -45.0  500 loci split (live)
   600 done |  20142 queued | MJD 61096.027778-61096.034722 RA   45.0-  60.0 Dec  -52.5- -48.8  271 loci accepted (live)
   608 done |  20136 queued | MJD 61096.027778-61096.034722 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
   609 done |  20137 queued | MJD 61096.027778-61096.034722 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.02777777778%2C+%22lt%22%3A+61096.034722222226%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-52.5%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=460&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf970a10140>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
   611 done |  20137 queued | MJD 61096.027778-61096.034722 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
   613 done |  20137 queued | MJD 61096.027778-61096.034722 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
   700 done |  20050 queued | MJD 61096.027778-61096.034722 RA  270.0- 285.0 Dec  -60.0- -30.0    0 loci accepted (live)
   754 done |  19998 queued | MJD 61096.034722-61096.041667 RA   45.0-  60.0 Dec  -60.0- -30.0  500 loci split (live)
   755 done |  19999 queued | MJD 61096.034722-61096.041667 RA   45.0-  60.0 Dec  -60.0- -45.0  500 loci split (live)
   757 done |  19999 queued | MJD 61096.034722-61096.041667 RA   45.0-  60.0 Dec  -52.5- -45.0  500 loci split (live)
   766 done |  19992 queued | MJD 61096.034722-61096.041667 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
      query failed attempt 1/6: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.034722222226%2C+%22lt%22%3A+61096.04166666667%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-60.0%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=220&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf97355e330>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
   767 done |  19993 queued | MJD 61096.034722-61096.041667 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
   769 done |  19993 queued | MJD 61096.034722-61096.041667 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
   771 done |  19993 queued | MJD 61096.034722-61096.041667 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
   800 done |  19964 queued | MJD 61096.034722-61096.041667 RA  120.0- 135.0 Dec    0.0-  30.0    0 loci accepted (live)
   900 done |  19864 queued | MJD 61096.041667-61096.048611 RA   15.0-  30.0 Dec  -60.0- -30.0    0 loci accepted (live)
   918 done |  19848 queued | MJD 61096.041667-61096.048611 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.04166666667%2C+%22lt%22%3A+61096.04861111112%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-60.0%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=100&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf95741d5e0>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
   919 done |  19849 queued | MJD 61096.041667-61096.048611 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
   921 done |  19849 queued | MJD 61096.041667-61096.048611 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
   923 done |  19849 queued | MJD 61096.041667-61096.048611 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
   924 done |  19850 queued | MJD 61096.041667-61096.048611 RA   60.0-  75.0 Dec  -48.8- -46.9  500 loci split (live)
  1000 done |  19774 queued | MJD 61096.041667-61096.048611 RA  240.0- 255.0 Dec  -60.0- -30.0    0 loci accepted (live)
  1100 done |  19674 queued | MJD 61096.048611-61096.055556 RA  120.0- 135.0 Dec   60.0-  90.0    0 loci accepted (live)
  1200 done |  19574 queued | MJD 61096.055556-61096.062500 RA   15.0-  30.0 Dec    0.0-  30.0    0 loci accepted (live)
  1300 done |  19474 queued | MJD 61096.055556-61096.062500 RA  270.0- 285.0 Dec  -60.0- -30.0    0 loci accepted (live)
  1360 done |  19416 queued | MJD 61096.062500-61096.069444 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  1361 done |  19417 queued | MJD 61096.062500-61096.069444 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
      query failed attempt 1/6: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.06250000001%2C+%22lt%22%3A+61096.06944444445%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-52.5%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=130&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf97355fef0>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1363 done |  19417 queued | MJD 61096.062500-61096.069444 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
  1365 done |  19417 queued | MJD 61096.062500-61096.069444 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
  1400 done |  19382 queued | MJD 61096.062500-61096.069444 RA  135.0- 150.0 Dec    0.0-  30.0    0 loci accepted (live)
  1500 done |  19282 queued | MJD 61096.069444-61096.076389 RA   30.0-  45.0 Dec  -60.0- -30.0    0 loci accepted (live)
  1512 done |  19272 queued | MJD 61096.069444-61096.076389 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  1513 done |  19273 queued | MJD 61096.069444-61096.076389 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.06944444445%2C+%22lt%22%3A+61096.0763888889%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-52.5%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=300&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf970d9a990>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1515 done |  19273 queued | MJD 61096.069444-61096.076389 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
  1517 done |  19273 queued | MJD 61096.069444-61096.076389 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
  1518 done |  19274 queued | MJD 61096.069444-61096.076389 RA   60.0-  75.0 Dec  -48.8- -46.9  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.06944444445%2C+%22lt%22%3A+61096.0763888889%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-46.875%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=120&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf98816f230>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1600 done |  19192 queued | MJD 61096.069444-61096.076389 RA  255.0- 270.0 Dec  -60.0- -30.0    0 loci accepted (live)
  1666 done |  19128 queued | MJD 61096.076389-61096.083333 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  1667 done |  19129 queued | MJD 61096.076389-61096.083333 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
  1669 done |  19129 queued | MJD 61096.076389-61096.083333 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.0763888889%2C+%22lt%22%3A+61096.08333333334%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-48.75%2C+%22lt%22%3A+-45.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=210&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf988194860>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1671 done |  19129 queued | MJD 61096.076389-61096.083333 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
  1700 done |  19100 queued | MJD 61096.076389-61096.083333 RA  120.0- 135.0 Dec    0.0-  30.0    0 loci accepted (live)
  1800 done |  19000 queued | MJD 61096.083333-61096.090278 RA   15.0-  30.0 Dec  -60.0- -30.0    0 loci accepted (live)
      query failed attempt 1/6: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.08333333334%2C+%22lt%22%3A+61096.09027777779%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+45.0%2C+%22lt%22%3A+60.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-60.0%2C+%22lt%22%3A+-30.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=160&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf9735d0a40>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1812 done |  18990 queued | MJD 61096.083333-61096.090278 RA   45.0-  60.0 Dec  -60.0- -30.0  500 loci split (live)
  1813 done |  18991 queued | MJD 61096.083333-61096.090278 RA   45.0-  60.0 Dec  -60.0- -45.0  500 loci split (live)
  1815 done |  18991 queued | MJD 61096.083333-61096.090278 RA   45.0-  60.0 Dec  -52.5- -45.0  500 loci split (live)
  1824 done |  18984 queued | MJD 61096.083333-61096.090278 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  1825 done |  18985 queued | MJD 61096.083333-61096.090278 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
  1827 done |  18985 queued | MJD 61096.083333-61096.090278 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
  1829 done |  18985 queued | MJD 61096.083333-61096.090278 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
      query failed attempt 1/6: HTTPConnectionPool(host='api.antares.noirlab.edu', port=80): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.08333333334%2C+%22lt%22%3A+61096.09027777779%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+60.0%2C+%22lt%22%3A+75.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-48.75%2C+%22lt%22%3A+-46.875%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D&page%5Boffset%5D=220&page%5Blimit%5D=10 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7bf95728bd70>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1830 done |  18986 queued | MJD 61096.083333-61096.090278 RA   60.0-  75.0 Dec  -48.8- -46.9  500 loci split (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61096.08333333334%2C+%22lt%22%3A+61096.09027777779%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+90.0%2C+%22lt%22%3A+105.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+0.0%2C+%22lt%22%3A+30.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf95741dc40>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1900 done |  18916 queued | MJD 61096.083333-61096.090278 RA  225.0- 240.0 Dec  -60.0- -30.0    0 loci accepted (live)
  1978 done |  18840 queued | MJD 61096.090278-61096.097222 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  1979 done |  18841 queued | MJD 61096.090278-61096.097222 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
  1981 done |  18841 queued | MJD 61096.090278-61096.097222 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)
  1983 done |  18841 queued | MJD 61096.090278-61096.097222 RA   60.0-  75.0 Dec  -48.8- -45.0  500 loci split (live)
  2000 done |  18824 queued | MJD 61096.090278-61096.097222 RA   90.0- 105.0 Dec    0.0-  30.0    0 loci accepted (live)
  2100 done |  18724 queued | MJD 61096.090278-61096.097222 RA  345.0- 360.0 Dec  -60.0- -30.0    0 loci accepted (live)
  2130 done |  18696 queued | MJD 61096.097222-61096.104167 RA   60.0-  75.0 Dec  -60.0- -30.0  500 loci split (live)
  2131 done |  18697 queued | MJD 61096.097222-61096.104167 RA   60.0-  75.0 Dec  -60.0- -45.0  500 loci split (live)
  2133 done |  18697 queued | MJD 61096.097222-61096.104167 RA   60.0-  75.0 Dec  -52.5- -45.0  500 loci split (live)

KeyboardInterrupt:

In [74]:
from pathlib import Path
import json
import time
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
from antares_client.search import search as antares_search, get_by_id

from src import history, query


# ============================================================
# USER SETTINGS
# ============================================================
DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")

# Change these for the one full night you want.
MJD_START = 61114.0
MJD_STOP = 61115.0

FETCH_LIGHTCURVES = True

# Probe-first strategy:
# If a tile returns 50 rows, assume it may contain more and split.
PROBE_LIMIT = 50
PROBE_THRESHOLD = 50

# Coarser initial grid than before; dense tiles split automatically.
TIME_BIN_MINUTES = 30
RA_BINS = 24
DEC_BINS = 6

MAX_RETRIES = 6
LIGHTCURVE_WORKERS = 4

# Safety floors. If a tile is still full below these, we refuse to call the night complete.
MIN_TIME_SECONDS = 30
MIN_RA_DEGREES = 0.05
MIN_DEC_DEGREES = 0.05

# New cache version so it does not mix with the earlier 500-row tile run.
CACHE_VERSION = "probe50_v1"


# ============================================================
# HELPERS
# ============================================================
def now_utc():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def retry_sleep(attempt):
    return [20, 60, 120, 240, 480][min(attempt - 1, 4)]


def frange(start, stop, step):
    x = float(start)
    while x < float(stop) - 1e-12:
        y = min(x + step, float(stop))
        yield x, y
        x = y


def query_tile_once(mjd_min, mjd_max, ra_min, ra_max, dec_min, dec_max, include_upper):
    upper_op = "lte" if include_upper else "lt"

    q = {
        "query": {
            "bool": {
                "filter": [
                    {
                        "range": {
                            "properties.newest_alert_observation_time": {
                                "gte": float(mjd_min),
                                upper_op: float(mjd_max),
                            }
                        }
                    },
                    {"range": {"ra": {"gte": float(ra_min), "lt": float(ra_max)}}},
                    {"range": {"dec": {"gte": float(dec_min), "lt": float(dec_max)}}},
                    query.lsst_identifier_filter(),
                ]
            }
        }
    }

    rows = []
    for locus in antares_search(q):
        rows.append(query.locus_to_record(locus))
        if len(rows) >= PROBE_LIMIT:
            break

    return pd.DataFrame(rows)


def query_tile_with_retry(*args):
    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            return query_tile_once(*args)
        except Exception as exc:
            last_error = exc
            print(f"      query failed attempt {attempt}/{MAX_RETRIES}: {exc}")
            if attempt < MAX_RETRIES:
                wait = retry_sleep(attempt)
                print(f"      sleeping {wait}s")
                time.sleep(wait)
    raise last_error


def tile_cache_path(cache_dir, tile):
    mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
    name = (
        f"mjd_{mjd0:.8f}_{mjd1:.8f}_"
        f"ra_{ra0:.4f}_{ra1:.4f}_"
        f"dec_{dec0:.4f}_{dec1:.4f}_"
        f"upper_{int(include_upper)}.parquet"
    ).replace(".", "p").replace("-", "m")
    return cache_dir / name


def split_tile(tile):
    mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
    time_seconds = (mjd1 - mjd0) * 86400.0
    ra_width = ra1 - ra0
    dec_width = dec1 - dec0

    # Sky-first splitting avoids deep pagination in dense observing strips.
    if dec_width > MIN_DEC_DEGREES * 1.01:
        mid = (dec0 + dec1) / 2.0
        return [
            (mjd0, mjd1, ra0, ra1, dec0, mid, include_upper),
            (mjd0, mjd1, ra0, ra1, mid, dec1, include_upper),
        ]

    if ra_width > MIN_RA_DEGREES * 1.01:
        mid = (ra0 + ra1) / 2.0
        return [
            (mjd0, mjd1, ra0, mid, dec0, dec1, include_upper),
            (mjd0, mjd1, mid, ra1, dec0, dec1, include_upper),
        ]

    if time_seconds > MIN_TIME_SECONDS * 1.01:
        mid = (mjd0 + mjd1) / 2.0
        return [
            (mjd0, mid, ra0, ra1, dec0, dec1, False),
            (mid, mjd1, ra0, ra1, dec0, dec1, include_upper),
        ]

    return []


def initial_tiles(mjd_start, mjd_stop):
    time_step = TIME_BIN_MINUTES / 1440.0
    ra_step = 360.0 / RA_BINS
    dec_step = 180.0 / DEC_BINS

    tiles = []
    for mjd0, mjd1 in frange(mjd_start, mjd_stop, time_step):
        include_upper = mjd1 >= mjd_stop
        for ra0, ra1 in frange(0.0, 360.0, ra_step):
            for dec0, dec1 in frange(-90.0, 90.0, dec_step):
                tiles.append((mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper))
    return tiles


def extract_full_loci_probe_first(data_root, mjd_start, mjd_stop):
    date_utc = history.mjd_to_utc_date(mjd_start)
    cache_dir = data_root / "cache" / CACHE_VERSION / "tile_loci" / date_utc
    cache_dir.mkdir(parents=True, exist_ok=True)

    pending = initial_tiles(mjd_start, mjd_stop)
    accepted_paths = []
    report_rows = []
    saturated_final = []
    done = 0
    t0 = time.time()

    print(f"Initial tiles: {len(pending):,}")
    print(f"Probe limit: {PROBE_LIMIT}; split if n >= {PROBE_THRESHOLD}")

    while pending:
        tile = pending.pop(0)
        mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper = tile
        path = tile_cache_path(cache_dir, tile)

        if path.exists():
            df = pd.read_parquet(path)
            source = "cache"
        else:
            df = query_tile_with_retry(mjd0, mjd1, ra0, ra1, dec0, dec1, include_upper)
            source = "live"

        n = len(df)
        saturated = n >= PROBE_THRESHOLD

        if saturated:
            children = split_tile(tile)
            if children:
                pending = children + pending
                status = "split"
            else:
                df.to_parquet(path, index=False)
                accepted_paths.append(path)
                saturated_final.append(tile)
                status = "accepted_saturated_final"
        else:
            df.to_parquet(path, index=False)
            accepted_paths.append(path)
            status = "accepted"

        done += 1
        report_rows.append({
            "mjd_min": mjd0,
            "mjd_max": mjd1,
            "ra_min": ra0,
            "ra_max": ra1,
            "dec_min": dec0,
            "dec_max": dec1,
            "include_upper": include_upper,
            "n_loci": n,
            "status": status,
            "source": source,
            "remaining": len(pending),
        })

        if done % 250 == 0 or saturated or status == "accepted_saturated_final":
            elapsed = time.time() - t0
            rate = done / elapsed if elapsed else 0
            print(
                f"{done:>6} done | {len(pending):>6} queued | "
                f"{rate:5.1f} tiles/s | "
                f"MJD {mjd0:.6f}-{mjd1:.6f} "
                f"RA {ra0:6.1f}-{ra1:6.1f} "
                f"Dec {dec0:6.1f}-{dec1:6.1f} "
                f"{n:>3} loci {status} ({source})"
            )

    frames = [pd.read_parquet(p) for p in accepted_paths]
    loci = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()

    if not loci.empty and "locus_id" in loci.columns:
        loci = loci.drop_duplicates("locus_id", keep="last").reset_index(drop=True)

    return loci, pd.DataFrame(report_rows), saturated_final


def fetch_one_lightcurve_cached(locus_id, label, cache_dir):
    path = cache_dir / f"{locus_id}.parquet"
    if path.exists():
        return pd.read_parquet(path), None

    last_error = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            locus = get_by_id(locus_id)
            lc = locus.lightcurve
            if lc is None or lc.empty:
                lc = pd.DataFrame({
                    "locus_id": [locus_id],
                    "range_label": [label],
                    "empty_lightcurve": [True],
                })
            else:
                lc = lc.copy()
                lc["locus_id"] = locus_id
                lc["range_label"] = label

            lc.to_parquet(path, index=False)
            return lc, None

        except Exception as exc:
            last_error = str(exc)
            if attempt < MAX_RETRIES:
                time.sleep(retry_sleep(attempt))

    return None, last_error


def fetch_all_lightcurves_cached(df_loci, date_utc, label, data_root):
    cache_dir = data_root / "cache" / CACHE_VERSION / "lightcurves" / date_utc
    cache_dir.mkdir(parents=True, exist_ok=True)

    locus_ids = df_loci["locus_id"].dropna().astype(str).drop_duplicates().tolist()
    frames = []
    failures = []

    print(f"Fetching {len(locus_ids):,} lightcurves with {LIGHTCURVE_WORKERS} workers")

    with ThreadPoolExecutor(max_workers=LIGHTCURVE_WORKERS) as pool:
        futures = {
            pool.submit(fetch_one_lightcurve_cached, lid, label, cache_dir): lid
            for lid in locus_ids
        }

        for i, future in enumerate(as_completed(futures), start=1):
            lid = futures[future]
            frame, err = future.result()

            if err:
                failures.append({"locus_id": lid, "error": err})
            elif frame is not None:
                frames.append(frame)

            if i % 100 == 0 or i == len(locus_ids):
                print(f"  {i}/{len(locus_ids)} lightcurves complete; failures={len(failures)}")

    alerts = pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()
    return alerts, pd.DataFrame(failures)


# ============================================================
# RUN ONE FULL NIGHT
# ============================================================
DATA_ROOT.mkdir(parents=True, exist_ok=True)

date_utc = history.mjd_to_utc_date(MJD_START)
label = f"Full History {history.display_date(date_utc)}"
paths = history.nightly_paths(DATA_ROOT, date_utc)
paths["dir"].mkdir(parents=True, exist_ok=True)

print(f"FULL NIGHT: {date_utc}")
print(f"MJD range : [{MJD_START}, {MJD_STOP}]")
print(f"Data root : {DATA_ROOT}")
print(f"Cache     : {CACHE_VERSION}")

started = now_utc()
t0 = time.time()

print("\nStage 1: probe-first full LSST-only locus extraction")
df_loci_raw, tile_report, saturated_final = extract_full_loci_probe_first(
    DATA_ROOT,
    MJD_START,
    MJD_STOP,
)

tile_report.to_parquet(paths["dir"] / f"tile_report_{CACHE_VERSION}.parquet", index=False)

if saturated_final:
    print(f"\nNOT COMPLETE: {len(saturated_final)} final saturated tiles remain.")
    print("Increase initial RA/Dec bins or lower MIN_RA_DEGREES/MIN_DEC_DEGREES, then rerun.")
    raise RuntimeError(f"{date_utc} has saturated final tiles; not accepting as complete.")

df_loci = history.prepare_loci(df_loci_raw, date_utc, MJD_START, MJD_STOP, now_utc())
df_loci.to_parquet(paths["loci"], index=False)

print(f"\nLoci complete: {len(df_loci):,}")

if FETCH_LIGHTCURVES:
    print("\nStage 2: full lightcurve extraction")
    df_alerts_raw, lc_failures = fetch_all_lightcurves_cached(
        df_loci,
        date_utc,
        label,
        DATA_ROOT,
    )

    if not lc_failures.empty:
        lc_failures.to_parquet(paths["dir"] / f"lightcurve_failures_{CACHE_VERSION}.parquet", index=False)
        raise RuntimeError(f"{len(lc_failures)} lightcurves failed after retries. Rerun this cell to resume.")

    df_alerts = history.prepare_alerts(df_alerts_raw, date_utc, label)
else:
    df_alerts = history.prepare_alerts(pd.DataFrame(), date_utc, label)

df_alerts.to_parquet(paths["alerts"], index=False)

validation = history.validation_summary(
    df_loci,
    df_alerts,
    mjd_min=MJD_START,
    mjd_max=MJD_STOP,
    lsst_only=True,
)

counts = query.lsst_identifier_counts(df_loci)

manifest = {
    "date_utc": date_utc,
    "mjd_min": float(MJD_START),
    "mjd_max": float(MJD_STOP),
    "query_tag": None,
    "target_loci": None,
    "actual_loci": int(len(df_loci)),
    "alert_rows": int(len(df_alerts)),
    "chunk_count": int((tile_report["status"].str.startswith("accepted")).sum()),
    "split_count": int((tile_report["status"] == "split").sum()),
    "saturated_chunk_count": 0,
    "status": "complete",
    "survey_mode": "lsst",
    "lsst_filter_used": True,
    "lsst_filter": query.lsst_identifier_filter(),
    "parallel_shards": 1,
    "lsst_dia_count": counts["lsst_dia_count"],
    "lsst_ss_count": counts["lsst_ss_count"],
    "ztf_object_id_count": counts["ztf_object_id_count"],
    "started_at_utc": started,
    "finished_at_utc": now_utc(),
    "runtime_seconds": round(time.time() - t0, 2),
    "validation": validation,
    "paths": {
        "loci": str(paths["loci"]),
        "alerts": str(paths["alerts"]),
        "manifest": str(paths["manifest"]),
    },
    "cache_version": CACHE_VERSION,
    "probe_limit": PROBE_LIMIT,
    "time_bin_minutes": TIME_BIN_MINUTES,
    "ra_bins": RA_BINS,
    "dec_bins": DEC_BINS,
}

with open(paths["manifest"], "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2, sort_keys=True)
    f.write("\n")

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("\nCOMPLETE")
print("Date:", date_utc)
print("Loci:", len(df_loci))
print("Alert/lightcurve rows:", len(df_alerts))
print("Runtime seconds:", manifest["runtime_seconds"])
display(nightly_summary.tail())

FULL NIGHT: 2026-03-15
MJD range : [61114.0, 61115.0]
Data root : /home/mdarim/ANTARES_Analysis_Data
Cache     : probe50_v1

Stage 1: probe-first full LSST-only locus extraction
Initial tiles: 6,912
Probe limit: 50; split if n >= 50
   250 done |   6662 queued |  17.4 tiles/s | MJD 61114.020833-61114.041667 RA  255.0- 270.0 Dec    0.0-  30.0   0 loci accepted (live)
   500 done |   6412 queued |  17.6 tiles/s | MJD 61114.062500-61114.083333 RA  165.0- 180.0 Dec  -60.0- -30.0   0 loci accepted (live)
   750 done |   6162 queued |  17.5 tiles/s | MJD 61114.104167-61114.125000 RA   60.0-  75.0 Dec   60.0-  90.0   0 loci accepted (live)
  1000 done |   5912 queued |  17.5 tiles/s | MJD 61114.125000-61114.145833 RA  330.0- 345.0 Dec    0.0-  30.0   0 loci accepted (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61114.14583333335%2C+%22lt%22%3A+61114.166666666686%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+30.0%2C+%22lt%22%3A+45.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+30.0%2C+%22lt%22%3A+60.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf7e0138e60>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  1250 done |   5662 queued |   8.2 tiles/s | MJD 61114.166667-61114.187500 RA  240.0- 255.0 Dec  -60.0- -30.0   0 loci accepted (live)
  1500 done |   5412 queued |   9.0 tiles/s | MJD 61114.208333-61114.229167 RA  135.0- 150.0 Dec   60.0-  90.0   0 loci accepted (live)
  1750 done |   5162 queued |   9.3 tiles/s | MJD 61114.250000-61114.270833 RA   45.0-  60.0 Dec    0.0-  30.0   0 loci accepted (live)
  2000 done |   4912 queued |   9.5 tiles/s | MJD 61114.270833-61114.291667 RA  315.0- 330.0 Dec  -60.0- -30.0   0 loci accepted (live)
      query failed attempt 1/6: HTTPSConnectionPool(host='api.antares.noirlab.edu', port=443): Max retries exceeded with url: /v1/loci?sort=-properties.newest_alert_observation_time&elasticsearch_query%5Blocus_listing%5D=%7B%22query%22%3A+%7B%22bool%22%3A+%7B%22filter%22%3A+%5B%7B%22range%22%3A+%7B%22properties.newest_alert_observation_time%22%3A+%7B%22gte%22%3A+61114.2916666667%2C+%22lt%22%3A+61114.31250000004%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22ra%22%3A+%7B%22gte%22%3A+75.0%2C+%22lt%22%3A+90.0%7D%7D%7D%2C+%7B%22range%22%3A+%7B%22dec%22%3A+%7B%22gte%22%3A+-30.0%2C+%22lt%22%3A+0.0%7D%7D%7D%2C+%7B%22bool%22%3A+%7B%22should%22%3A+%5B%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.dia_object_id%22%7D%7D%2C+%7B%22exists%22%3A+%7B%22field%22%3A+%22properties.survey.lsst.ss_object_id%22%7D%7D%5D%2C+%22minimum_should_match%22%3A+1%7D%7D%5D%7D%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7bf7dc0e38c0>, 'Connection to api.antares.noirlab.edu timed out. (connect timeout=60)'))
      sleeping 20s
  2250 done |   4662 queued |   7.3 tiles/s | MJD 61114.312500-61114.333333 RA  210.0- 225.0 Dec   60.0-  90.0   0 loci accepted (live)
  2500 done |   4412 queued |   7.8 tiles/s | MJD 61114.354167-61114.375000 RA  120.0- 135.0 Dec    0.0-  30.0   0 loci accepted (live)
  2750 done |   4162 queued |   8.2 tiles/s | MJD 61114.395833-61114.416667 RA   30.0-  45.0 Dec  -60.0- -30.0   0 loci accepted (live)
  3000 done |   3912 queued |   8.4 tiles/s | MJD 61114.416667-61114.437500 RA  285.0- 300.0 Dec   60.0-  90.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
      query failed attempt 2/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 60s
  3250 done |   3662 queued |   6.6 tiles/s | MJD 61114.458333-61114.479167 RA  195.0- 210.0 Dec    0.0-  30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  3500 done |   3412 queued |   6.4 tiles/s | MJD 61114.500000-61114.520833 RA  105.0- 120.0 Dec  -60.0- -30.0   0 loci accepted (live)
  3750 done |   3162 queued |   6.7 tiles/s | MJD 61114.541667-61114.562500 RA    0.0-  15.0 Dec   60.0-  90.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  4000 done |   2912 queued |   6.6 tiles/s | MJD 61114.562500-61114.583333 RA  270.0- 285.0 Dec    0.0-  30.0   0 loci accepted (live)
  4250 done |   2662 queued |   6.9 tiles/s | MJD 61114.604167-61114.625000 RA  180.0- 195.0 Dec  -60.0- -30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  4500 done |   2412 queued |   6.8 tiles/s | MJD 61114.645833-61114.666667 RA   75.0-  90.0 Dec   60.0-  90.0   0 loci accepted (live)
  4750 done |   2162 queued |   7.0 tiles/s | MJD 61114.666667-61114.687500 RA  345.0- 360.0 Dec    0.0-  30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  5000 done |   1912 queued |   6.9 tiles/s | MJD 61114.708333-61114.729167 RA  255.0- 270.0 Dec  -60.0- -30.0   0 loci accepted (live)
  5250 done |   1662 queued |   7.1 tiles/s | MJD 61114.750000-61114.770833 RA  150.0- 165.0 Dec   60.0-  90.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  5500 done |   1412 queued |   6.9 tiles/s | MJD 61114.791667-61114.812500 RA   60.0-  75.0 Dec    0.0-  30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  5750 done |   1162 queued |   6.8 tiles/s | MJD 61114.812500-61114.833333 RA  330.0- 345.0 Dec  -60.0- -30.0   0 loci accepted (live)
  6000 done |    912 queued |   7.0 tiles/s | MJD 61114.854167-61114.875000 RA  225.0- 240.0 Dec   60.0-  90.0   0 loci accepted (live)
  6250 done |    662 queued |   7.2 tiles/s | MJD 61114.895833-61114.916667 RA  135.0- 150.0 Dec    0.0-  30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  6500 done |    412 queued |   7.1 tiles/s | MJD 61114.937500-61114.958333 RA   45.0-  60.0 Dec  -60.0- -30.0   0 loci accepted (live)
      query failed attempt 1/6: {'errors': [{'detail': 'A server-side problem occured.', 'status': 500, 'title': 'Internal Server Error'}]}
      sleeping 20s
  6750 done |    162 queued |   7.0 tiles/s | MJD 61114.958333-61114.979167 RA  300.0- 315.0 Dec   60.0-  90.0   0 loci accepted (live)

Loci complete: 10

Stage 2: full lightcurve extraction
Fetching 10 lightcurves with 4 workers
  10/10 lightcurves complete; failures=0

COMPLETE
Date: 2026-03-15
Loci: 10
Alert/lightcurve rows: 2818
Runtime seconds: 999.27

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
16,2026-03-13,2026/3/13,61112.0,61113.0,None,None,5,438,6912,0,...,5,5,True,True,949.95,2026-05-29T00:09:54+00:00,2026-05-29T00:25:44+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
17,2026-03-14,2026/3/14,61113.0,61114.0,None,None,2,82,6912,0,...,2,2,True,True,926.11,2026-05-29T00:43:16+00:00,2026-05-29T00:58:43+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
18,2026-03-15,2026/3/15,61114.0,61115.0,None,None,10,2818,6912,0,...,10,10,True,True,999.27,2026-05-29T01:15:36+00:00,2026-05-29T01:32:15+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
19,2026-05-25,2026/5/25,61185.0,61186.0,None,None,49926,1527986,9625,2713,...,49926,49926,True,True,199.40,2026-05-26T18:25:29+00:00,2026-05-26T18:28:48+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
20,2026-05-27,2026/5/27,61187.0,61188.0,None,None,25092,254055,8279,1367,...,25092,25092,True,True,123.16,2026-05-28T15:11:27+00:00,2026-05-28T15:13:30+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...

## 4. Nightly Update

This ingests the newest night, compares it against prior cumulative history, and appends it only after validation passes.

In [35]:
RUN_NIGHTLY_UPDATE = True

if RUN_NIGHTLY_UPDATE:
    nightly_result = history.run_nightly_update(
        data_root=DATA_ROOT,
        mjd_min=config.MJD1_MIN,
        mjd_max=config.MJD1_MAX,
        target_loci=config.HISTORY_TARGET_LOCI,
        fetch_lightcurves=config.HISTORY_FETCH_ALL_LIGHTCURVES,
        resume=True,
    )
    print(nightly_result['comparison'])
    print(nightly_result['manifest']['status'])

  Parent shards: 3 non-overlapping workers
  Chunked query 'Last Night 2026/5/21 shard 1/3'  MJD [61181.000000, 61181.333333]
    ES limit=10,000, split at >= 9,500, minimum chunk=30s
  Chunked query 'Last Night 2026/5/21 shard 2/3'  MJD [61181.333333, 61181.666667]
    ES limit=10,000, split at >= 9,500, minimum chunk=30s
  Chunked query 'Last Night 2026/5/21 shard 3/3'  MJD [61181.666667, 61182.000000]
    ES limit=10,000, split at >= 9,500, minimum chunk=30s
       1. 61181.666667-61182.000000   28800.0s       0 loci  accepted  (live; 0 queued)
  Last Night 2026/5/21 shard 3/3: 0 unique loci from 1 accepted chunks  (0 splits, 0.3s)
       1. 61181.333333-61181.666667   28800.0s       0 loci  accepted  (live; 0 queued)
  Last Night 2026/5/21 shard 2/3: 0 unique loci from 1 accepted chunks  (0 splits, 0.3s)
       1. 61181.000000-61181.333333   28800.0s      16 loci  accepted  (live; 0 queued)
  Last Night 2026/5/21 shard 1/3: 15 unique loci from 1 accepted chunks  (0 splits, 0.4s)
  Last Night 2026/5/21: 15 unique loci after shard merge (0 splits, 0.4s)
  Fetching 15 lightcurves for 'Last Night 2026/5/21' (up to 16 parallel workers) ...
    15/15  (0 errors)  3s elapsed  (5.0 loci/s)
  Last Night 2026/5/21: 10,419 alert rows from 15 loci  (0 errors)  [3.0s total]
{'night_loci': 15, 'cumulative_loci_rows': 209697, 'cumulative_unique_loci': 209697, 'overlap_loci': 0, 'overlap_fraction_of_night': 0.0, 'new_loci': 15}
under_target

## 5. Inspect Stored Data

In [75]:
loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)
print(f'Cumulative index rows: {len(loci_index):,}')
display(nightly_summary.tail(20))

Cumulative index rows: 349,325

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
1,2026-02-26,2026/2/26,61097.0,61098.0,None,None,96238,933004,11853,4941,...,96238,96238,True,True,24377.58,2026-05-25T09:23:14+00:00,2026-05-25T16:09:32+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
2,2026-02-27,2026/2/27,61098.0,61099.0,None,None,47909,1590484,8952,2040,...,47909,47909,True,True,11109.51,2026-05-25T17:46:27+00:00,2026-05-25T20:51:36+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
3,2026-02-28,2026/2/28,61099.0,61100.0,None,None,2919,139630,7017,105,...,2919,2919,True,True,1534.53,2026-05-26T00:14:24+00:00,2026-05-26T00:39:58+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
4,2026-03-01,2026/3/1,61100.0,61101.0,None,None,1361,138097,6958,46,...,1361,1361,True,True,1174.79,2026-05-26T00:44:59+00:00,2026-05-26T01:04:34+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
5,2026-03-02,2026/3/2,61101.0,61102.0,None,None,1531,87575,6970,58,...,1531,1531,True,True,1200.71,2026-05-26T01:12:01+00:00,2026-05-26T01:32:01+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
6,2026-03-03,2026/3/3,61102.0,61103.0,None,None,675,57283,6939,27,...,675,675,True,True,984.66,2026-05-26T01:37:27+00:00,2026-05-26T01:53:51+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
7,2026-03-04,2026/3/4,61103.0,61104.0,None,None,239,2530,6921,9,...,239,239,True,True,985.27,2026-05-28T05:54:42+00:00,2026-05-28T06:11:08+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
8,2026-03-05,2026/3/5,61104.0,61105.0,None,None,0,0,6912,0,...,0,0,False,True,973.44,2026-05-28T06:13:41+00:00,2026-05-28T06:29:55+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
9,2026-03-06,2026/3/6,61105.0,61106.0,None,None,2349,100660,6994,82,...,2349,2349,True,True,1484.29,2026-05-28T06:40:56+00:00,2026-05-28T07:05:40+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
10,2026-03-07,2026/3/7,61106.0,61107.0,None,None,1680,17475,6967,55,...,1680,1680,True,True,1251.74,2026-05-28T07:17:38+00:00,2026-05-28T07:38:30+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
11,2026-03-08,2026/3/8,61107.0,61108.0,None,None,2357,127312,6997,85,...,2357,2357,True,True,1339.17,2026-05-28T07:42:15+00:00,2026-05-28T08:04:34+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
12,2026-03-09,2026/3/9,61108.0,61109.0,None,None,2893,44822,7013,101,...,2893,2893,True,True,1518.43,2026-05-28T08:08:04+00:00,2026-05-28T08:33:22+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
13,2026-03-10,2026/3/10,61109.0,61110.0,None,None,674,5492,6943,31,...,674,674,True,True,1021.88,2026-05-28T23:04:44+00:00,2026-05-28T23:21:46+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
14,2026-03-11,2026/3/11,61110.0,61111.0,None,None,0,0,6912,0,...,0,0,False,True,101.51,2026-05-28T23:43:45+00:00,2026-05-28T23:45:27+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
15,2026-03-12,2026/3/12,61111.0,61112.0,None,None,6,301,6912,0,...,6,6,True,True,959.31,2026-05-28T23:49:29+00:00,2026-05-29T00:05:28+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
16,2026-03-13,2026/3/13,61112.0,61113.0,None,None,5,438,6912,0,...,5,5,True,True,949.95,2026-05-29T00:09:54+00:00,2026-05-29T00:25:44+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
17,2026-03-14,2026/3/14,61113.0,61114.0,None,None,2,82,6912,0,...,2,2,True,True,926.11,2026-05-29T00:43:16+00:00,2026-05-29T00:58:43+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
18,2026-03-15,2026/3/15,61114.0,61115.0,None,None,10,2818,6912,0,...,10,10,True,True,999.27,2026-05-29T01:15:36+00:00,2026-05-29T01:32:15+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
19,2026-05-25,2026/5/25,61185.0,61186.0,None,None,49926,1527986,9625,2713,...,49926,49926,True,True,199.40,2026-05-26T18:25:29+00:00,2026-05-26T18:28:48+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...
20,2026-05-27,2026/5/27,61187.0,61188.0,None,None,25092,254055,8279,1367,...,25092,25092,True,True,123.16,2026-05-28T15:11:27+00:00,2026-05-28T15:13:30+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...

In [30]:
from pathlib import Path
import json
import pandas as pd
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")
KEEP_DATE = "2026-02-25"

manifest_path = DATA_ROOT / "data" / "lsst_only" / "nightly" / "2026" / "02" / "25" / "manifest.json"
loci_path = DATA_ROOT / "data" / "lsst_only" / "nightly" / "2026" / "02" / "25" / "loci.parquet"
alerts_path = DATA_ROOT / "data" / "lsst_only" / "nightly" / "2026" / "02" / "25" / "alerts.parquet"

with open(manifest_path, "r") as f:
    manifest = json.load(f)

print("Manifest:")
for key in ["date_utc", "mjd_min", "mjd_max", "target_loci", "actual_loci", "alert_rows", "status"]:
    print(key, "=", manifest.get(key))

print("\nFiles exist:")
print("loci:", loci_path.exists(), loci_path)
print("alerts:", alerts_path.exists(), alerts_path)

print("\nParquet row counts:")
print("loci rows:", len(pd.read_parquet(loci_path)))
print("alert rows:", len(pd.read_parquet(alerts_path)))

Manifest:
date_utc = 2026-02-25
mjd_min = 61096.0
mjd_max = 61097.0
target_loci = None
actual_loci = 113459
alert_rows = 1012223
status = complete

Files exist:
loci: True /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/loci.parquet
alerts: True /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/25/alerts.parquet

Parquet row counts:
loci rows: 113459
alert rows: 1012223

In [32]:
from pathlib import Path
import shutil
from datetime import datetime, timezone

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")
KEEP_PARTS = ("2026", "02", "25")
KEEP_DATE = "2026-02-25"

DRY_RUN = False

timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
quarantine = DATA_ROOT / "_quarantine_before_delete" / timestamp

paths_to_move = []

nightly_root = DATA_ROOT / "data" / "lsst_only" / "nightly"
for day_dir in sorted(nightly_root.glob("*/*/*")):
    if day_dir.is_dir() and day_dir.parts[-3:] != KEEP_PARTS:
        paths_to_move.append(day_dir)

cumulative_root = DATA_ROOT / "data" / "lsst_only" / "cumulative"
if cumulative_root.exists():
    paths_to_move.append(cumulative_root)

cache_root = DATA_ROOT / "cache"
if cache_root.exists():
    for item in sorted(cache_root.iterdir()):
        if item.name != "probe50_v1":
            paths_to_move.append(item)
        else:
            for sub in sorted(item.glob("*/*")):
                if sub.is_dir() and sub.name != KEEP_DATE:
                    paths_to_move.append(sub)

print("Will quarantine:")
for p in paths_to_move:
    print(" ", p)

print("\nDestination:")
print(quarantine)

if DRY_RUN:
    print("\nDRY_RUN=True, nothing moved.")
else:
    quarantine.mkdir(parents=True, exist_ok=True)
    for src in paths_to_move:
        if src.exists():
            dst = quarantine / src.relative_to(DATA_ROOT)
            dst.parent.mkdir(parents=True, exist_ok=True)
            print(f"Moving {src} -> {dst}")
            shutil.move(str(src), str(dst))

Will quarantine:
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/24
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/26
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/27
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/28
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/05/21
  /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/cumulative
  /home/mdarim/ANTARES_Analysis_Data/cache/chunks
  /home/mdarim/ANTARES_Analysis_Data/cache/full_loci_chunks
  /home/mdarim/ANTARES_Analysis_Data/cache/tile_loci

Destination:
/home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/24 -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/nightly/2026/02/24
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/26 -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/nightly/2026/02/26
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/27 -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/nightly/2026/02/27
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/02/28 -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/nightly/2026/02/28
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/nightly/2026/05/21 -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/nightly/2026/05/21
Moving /home/mdarim/ANTARES_Analysis_Data/data/lsst_only/cumulative -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/data/lsst_only/cumulative
Moving /home/mdarim/ANTARES_Analysis_Data/cache/chunks -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/cache/chunks
Moving /home/mdarim/ANTARES_Analysis_Data/cache/full_loci_chunks -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/cache/full_loci_chunks
Moving /home/mdarim/ANTARES_Analysis_Data/cache/tile_loci -> /home/mdarim/ANTARES_Analysis_Data/_quarantine_before_delete/20260525T091133Z/cache/tile_loci

In [33]:
from pathlib import Path
from src import history

DATA_ROOT = Path("/home/mdarim/ANTARES_Analysis_Data")

loci_index, nightly_summary = history.update_cumulative_indexes(DATA_ROOT)

print("Cumulative loci rows:", len(loci_index))
display(nightly_summary)

Cumulative loci rows: 113459

,date_utc,display_date,mjd_min,mjd_max,query_tag,target_loci,actual_loci,alert_rows,chunk_count,split_count,...,lsst_ss_count,ztf_object_id_count,lsst_only_pass,history_start_pass,runtime_seconds,started_at_utc,finished_at_utc,loci_path,alerts_path,manifest_path
0,2026-02-25,2026/2/25,61096.0,61097.0,None,None,113459,1012223,12835,5923,...,113459,113459,True,True,27835.51,2026-05-25T00:21:24+00:00,2026-05-25T08:05:19+00:00,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...,/home/mdarim/ANTARES_Analysis_Data/data/lsst_o...